// 東高３年 英単語やったんぞ - 単語データ (2233語)
window.WORDS = [
{no:1,en:"weather",ja:"（特定の場所の一時的な）天気"},
{no:2,en:"temperature",ja:"温度"},
{no:3,en:"wind",ja:"風"},
{no:4,en:"ray",ja:"光線"},
{no:5,en:"view",ja:"眺め"},
{no:6,en:"fine",ja:"晴れた"},
{no:7,en:"calm",ja:"穏やかな"},
{no:8,en:"answer",ja:"に答える"},
{no:9,en:"approach",ja:"に近づく"},
{no:10,en:"attend",ja:"に出席する"},
{no:11,en:"discuss",ja:"について議論する"},
{no:12,en:"enter",ja:"に入る"},
{no:13,en:"plant",ja:"植物"},
{no:14,en:"blossom",ja:"（果樹の）花"},
{no:15,en:"bloom",ja:"（観賞用の）花"},
{no:16,en:"leaf",ja:"葉"},
{no:17,en:"fruit",ja:"果物"},
{no:18,en:"pick",ja:"（花・実など）を摘む"},
{no:19,en:"grow",ja:"成長する"},
{no:20,en:"marry",ja:"と結婚する"},
{no:21,en:"mention",ja:"…と述べる"},
{no:22,en:"obey",ja:"に従う"},
{no:23,en:"reach",ja:"に達する"},
{no:24,en:"resemble",ja:"に似ている"},
{no:25,en:"survive",ja:"を生き延びる"},
{no:26,en:"continent",ja:"大陸"},
{no:27,en:"area",ja:"（ある特定の）地域"},
{no:28,en:"part",ja:"部分"},
{no:29,en:"horizon",ja:"地平線"},
{no:30,en:"border",ja:"国境"},
{no:31,en:"foreign",ja:"外国の"},
{no:32,en:"apologize",ja:"謝罪する"},
{no:33,en:"argue",ja:"言い争う"},
{no:34,en:"complain",ja:"不平を言う"},
{no:35,en:"graduate",ja:"卒業する"},
{no:36,en:"agree",ja:"意見が一致する"},
{no:37,en:"creature",ja:"生き物"},
{no:38,en:"tail",ja:"尾"},
{no:39,en:"alive",ja:"生きている"},
{no:40,en:"bite",ja:"をかむ"},
{no:41,en:"dig",ja:"（地面・穴など）を掘る"},
{no:42,en:"feel",ja:"～の感じがする"},
{no:43,en:"smell",ja:"～のにおいがする"},
{no:44,en:"taste",ja:"～の味がする"},
{no:45,en:"seem",ja:"～のように思われる"},
{no:46,en:"look",ja:"～のように見える"},
{no:47,en:"appear",ja:"～のように見える"},
{no:48,en:"relationship",ja:"関係"},
{no:49,en:"population",ja:"人口"},
{no:50,en:"generation",ja:"世代"},
{no:51,en:"hero",ja:"英雄"},
{no:52,en:"trust",ja:"を信頼する"},
{no:53,en:"village",ja:"村"},
{no:54,en:"common",ja:"共通の"},
{no:55,en:"public",ja:"公共の"},
{no:56,en:"give",ja:"を与える"},
{no:57,en:"send",ja:"を送る"},
{no:58,en:"show",ja:"を見せる"},
{no:59,en:"pass",ja:"を手渡す"},
{no:60,en:"society",ja:"社会"},
{no:61,en:"culture",ja:"文化"},
{no:62,en:"custom",ja:"（社会的な）慣習"},
{no:63,en:"tradition",ja:"伝統"},
{no:64,en:"rule",ja:"規則"},
{no:65,en:"role",ja:"役割"},
{no:66,en:"address",ja:"住所"},
{no:67,en:"ceremony",ja:"式"},
{no:68,en:"cash",ja:"現金"},
{no:69,en:"buy",ja:"を買う"},
{no:70,en:"cook",ja:"（を）料理する"},
{no:71,en:"choose",ja:"を選ぶ"},
{no:72,en:"get",ja:"を得る"},
{no:73,en:"proud",ja:"誇りに思って"},
{no:74,en:"grateful",ja:"感謝して"},
{no:75,en:"afraid",ja:"恐れて"},
{no:76,en:"anxious",ja:"心配して"},
{no:77,en:"ashamed",ja:"恥じて"},
{no:78,en:"angry",ja:"怒って"},
{no:79,en:"miserable",ja:"みじめな"},
{no:80,en:"ask",ja:"を尋ねる"},
{no:81,en:"cost",ja:"（費用）がかかる"},
{no:82,en:"save",ja:"を省く"},
{no:83,en:"envy",ja:"をうらやむ"},
{no:84,en:"spare",ja:"（時間）をさく"},
{no:85,en:"age",ja:"年齢"},
{no:86,en:"kid",ja:"子ども"},
{no:87,en:"cousin",ja:"いとこ"},
{no:88,en:"host",ja:"（男）主人（役）"},
{no:89,en:"female",ja:"女性"},
{no:90,en:"male",ja:"男性"},
{no:91,en:"human",ja:"人間"},
{no:92,en:"owe",ja:"（お金）を借りている"},
{no:93,en:"allow",ja:"を許す"},
{no:94,en:"cause",ja:"（苦痛・被害）をもたらす"},
{no:95,en:"charge",ja:"（代金）を請求する"},
{no:96,en:"loan",ja:"（お金）を貸し付ける"},
{no:97,en:"false",ja:"誤った"},
{no:98,en:"bitter",ja:"つらい"},
{no:99,en:"empty",ja:"からの"},
{no:100,en:"short",ja:"不足した"},
{no:101,en:"absent",ja:"不在で"},
{no:102,en:"waste",ja:"（お金・時間）をむだに使う"},
{no:103,en:"trouble",ja:"を悩ませる"},
{no:104,en:"leave",ja:"を～のままにしておく"},
{no:105,en:"find",ja:"が～だとわかる"},
{no:106,en:"elect",ja:"を～に選出する"},
{no:107,en:"believe",ja:"が～だと思う"},
{no:108,en:"tourist",ja:"観光客"},
{no:109,en:"travel",ja:"旅行する"},
{no:110,en:"voyage",ja:"航海"},
{no:111,en:"rest",ja:"休息"},
{no:112,en:"leisure",ja:"余暇"},
{no:113,en:"airport",ja:"空港"},
{no:114,en:"abroad",ja:"外国へ"},
{no:115,en:"sightseeing",ja:"観光"},
{no:116,en:"rise",ja:"上がる"},
{no:117,en:"raise",ja:"を上げる"},
{no:118,en:"lie",ja:"横たわる"},
{no:119,en:"lay",ja:"を横たえる"},
{no:120,en:"conversation",ja:"会話"},
{no:121,en:"speech",ja:"演説"},
{no:122,en:"attention",ja:"注意"},
{no:123,en:"contact",ja:"接触"},
{no:124,en:"remain",ja:"～のままである"},
{no:125,en:"own",ja:"を所有している"},
{no:126,en:"belong",ja:"…に所属している"},
{no:127,en:"contain",ja:"を含む"},
{no:128,en:"exist",ja:"存在する"},
{no:129,en:"hate",ja:"を憎む"},
{no:130,en:"understand",ja:"を理解する"},
{no:131,en:"subject",ja:"話題"},
{no:132,en:"fake",ja:"にせの"},
{no:133,en:"opinion",ja:"意見"},
{no:134,en:"fact",ja:"事実"},
{no:135,en:"example",ja:"例"},
{no:136,en:"reason",ja:"理由"},
{no:137,en:"knowledge",ja:"知識"},
{no:138,en:"make",ja:"…に～させる【強制】"},
{no:139,en:"let",ja:"…に～させる【許可】"},
{no:140,en:"have",ja:"…に～させる【依頼】"},
{no:141,en:"stranger",ja:"見知らぬ人"},
{no:142,en:"safe",ja:"安全な"},
{no:143,en:"copy",ja:"（本や印刷物の）～部"},
{no:144,en:"line",ja:"職業"},
{no:145,en:"word",ja:"約束"},
{no:146,en:"ring",ja:"（ベル・電話などが）鳴ること"},
{no:147,en:"hear",ja:"が聞こえる"},
{no:148,en:"listen",ja:"（注意して）…を聴く"},
{no:149,en:"see",ja:"（が）見える"},
{no:150,en:"watch",ja:"（を）よく見る"},
{no:151,en:"situation",ja:"状況"},
{no:152,en:"position",ja:"位置"},
{no:153,en:"front",ja:"前部"},
{no:154,en:"bottom",ja:"（最）下部"},
{no:155,en:"neighborhood",ja:"近所"},
{no:156,en:"point",ja:"点"},
{no:157,en:"want",ja:"にしてほしいと思っている"},
{no:158,en:"enable",ja:"に～することを可能にする"},
{no:159,en:"persuade",ja:"を説得して～させる"},
{no:160,en:"encourage",ja:"に～するように励ます"},
{no:161,en:"expect",ja:"が～するだろうと思う"},
{no:162,en:"invite",ja:"に～するように依頼する"},
{no:163,en:"clothes",ja:"服"},
{no:164,en:"comb",ja:"くし"},
{no:165,en:"grocery",ja:"食料品店"},
{no:166,en:"gift",ja:"贈り物"},
{no:167,en:"seat",ja:"座席"},
{no:168,en:"cover",ja:"カバー"},
{no:169,en:"force",ja:"に～することを強制する"},
{no:170,en:"compel",ja:"に～することを強いる"},
{no:171,en:"oblige",ja:"に～することを義務づける"},
{no:172,en:"require",ja:"に～するように要求する"},
{no:173,en:"permit",ja:"が～することを許す"},
{no:174,en:"factory",ja:"工場"},
{no:175,en:"museum",ja:"博物館"},
{no:176,en:"store",ja:"店"},
{no:177,en:"office",ja:"事務所"},
{no:178,en:"story",ja:"（建物の）階"},
{no:179,en:"frame",ja:"骨組み"},
{no:180,en:"afford",ja:"～する余裕がある"},
{no:181,en:"attempt",ja:"～することを試みる"},
{no:182,en:"fail",ja:"～しそこなう"},
{no:183,en:"hope",ja:"～したいと思う"},
{no:184,en:"intend",ja:"～するつもりである"},
{no:185,en:"manage",ja:"どうにかして～する"},
{no:186,en:"nature",ja:"自然"},
{no:187,en:"source",ja:"水源"},
{no:188,en:"desert",ja:"砂漠"},
{no:189,en:"space",ja:"宇宙"},
{no:190,en:"even",ja:"（表面などが）平らな"},
{no:191,en:"pretend",ja:"～するふりをする"},
{no:192,en:"refuse",ja:"～することを拒む"},
{no:193,en:"promise",ja:"～することを約束する"},
{no:194,en:"offer",ja:"～することを申し出る"},
{no:195,en:"desire",ja:"～することを強く望む"},
{no:196,en:"plan",ja:"～することを計画する"},
{no:197,en:"chance",ja:"（偶然の）機会"},
{no:198,en:"courage",ja:"勇気"},
{no:199,en:"familiar",ja:"よく知られた"},
{no:200,en:"sure",ja:"確信して"},
{no:201,en:"true",ja:"本当の"},
{no:202,en:"enjoy",ja:"～して楽しむ"},
{no:203,en:"avoid",ja:"～するのを避ける"},
{no:204,en:"finish",ja:"～し終える"},
{no:205,en:"mind",ja:"（を）いやだと思う"},
{no:206,en:"stop",ja:"～するのをやめる"},
{no:207,en:"close",ja:"近い"},
{no:208,en:"far",ja:"遠い"},
{no:209,en:"distant",ja:"遠い"},
{no:210,en:"upstairs",ja:"階上に"},
{no:211,en:"forgive",ja:"（を）許す"},
{no:212,en:"practice",ja:"～する練習をする"},
{no:213,en:"consider",ja:"～するのをよく考える"},
{no:214,en:"escape",ja:"～するのをまぬがれる"},
{no:215,en:"admit",ja:"～したのを認める"},
{no:216,en:"deny",ja:"～したのを否定する"},
{no:217,en:"miss",ja:"～しそこなう"},
{no:218,en:"important",ja:"重要な"},
{no:219,en:"precious",ja:"貴重な"},
{no:220,en:"main",ja:"おもな"},
{no:221,en:"perfect",ja:"完全な"},
{no:222,en:"need",ja:"を必要とする"},
{no:223,en:"remember",ja:"を覚えている"},
{no:224,en:"forget",ja:"を忘れる"},
{no:225,en:"try",ja:"を試みる"},
{no:226,en:"regret",ja:"を後悔する"},
{no:227,en:"certain",ja:"確実な"},
{no:228,en:"likely",ja:"ありそうな"},
{no:229,en:"almost",ja:"ほとんど"},
{no:230,en:"become",ja:"に似合う"},
{no:231,en:"count",ja:"重要である"},
{no:232,en:"face",ja:"（困難など）に直面する"},
{no:233,en:"follow",ja:"…ということになる"},
{no:234,en:"last",ja:"続く"},
{no:235,en:"run",ja:"を経営する"},
{no:236,en:"stand",ja:"をがまんする"},
{no:237,en:"cast",ja:"（ものを）投げる"},
{no:238,en:"pay",ja:"得になる"},
{no:239,en:"read",ja:"解釈される"},
{no:240,en:"sell",ja:"売れる"},
{no:241,en:"change",ja:"つり銭"},
{no:242,en:"mine",ja:"鉱山"},
{no:243,en:"fire",ja:"を解雇する"},
{no:244,en:"book",ja:"（を）予約する"},
{no:245,en:"charm",ja:"お守り"},
{no:246,en:"break",ja:"休憩"},
{no:247,en:"hand",ja:"を手渡す"},
{no:248,en:"place",ja:"地位"},
{no:249,en:"flat",ja:"パンクした"},
{no:250,en:"lot",ja:"運命"},
{no:251,en:"will",ja:"遺言（書）"},
{no:252,en:"well",ja:"井戸"},
{no:253,en:"end",ja:"目的"},
{no:254,en:"edge",ja:"有利な状況・立場"},
{no:255,en:"table",ja:"表"},
{no:256,en:"spell",ja:"期間"},
{no:257,en:"touch",ja:"少量"},
{no:258,en:"game",ja:"獲物"},
{no:259,en:"room",ja:"場所"},
{no:260,en:"match",ja:"（と）調和する"},
{no:261,en:"fall",ja:"秋"},
{no:262,en:"park",ja:"駐車する"},
{no:263,en:"be made from ...",ja:"（原料）から作られている"},
{no:264,en:"be made of ...",ja:"（材料）でできている"},
{no:265,en:"be made up of ...",ja:"…で構成されている"},
{no:266,en:"make ... into～",ja:"…を（製品）に加工する"},
{no:267,en:"make up one's mind to do",ja:"～しようと決心する"},
{no:268,en:"make a point of -ing",ja:"～することにしている"},
{no:269,en:"make progress in ...",ja:"…において進歩をとげる"},
{no:270,en:"come across ...",ja:"…に出くわす"},
{no:271,en:"come true",ja:"実現する"},
{no:272,en:"come to (oneself)",ja:"意識を取り戻す"},
{no:273,en:"come to do",ja:"するようになる"},
{no:274,en:"come off",ja:"行われる"},
{no:275,en:"come to think of it",ja:"考えてみると"},
{no:276,en:"come by (...)",ja:"…を手に入れる"},
{no:277,en:"go on -ing",ja:"～し続ける"},
{no:278,en:"go on to do",ja:"さらに続けて～する"},
{no:279,en:"go on with ...",ja:"…を続ける"},
{no:280,en:"go -ing",ja:"～しに行く"},
{no:281,en:"go through ...",ja:"…を経験する"},
{no:282,en:"go bad",ja:"（食べ物などが）腐る"},
{no:283,en:"go wild",ja:"荒っぽくなる"},
{no:284,en:"go from bad to worse",ja:"さらに悪くなる"},
{no:285,en:"go ahead with ...",ja:"…を始める"},
{no:286,en:"go over ...",ja:"…をよく調べる"},
{no:287,en:"go with ...",ja:"…と調和する"},
{no:288,en:"go out of one's way to do",ja:"わざわざ～する"},
{no:289,en:"be on the go",ja:"仕事に追われている"},
{no:290,en:"give〈人〉a hand",ja:"〈人〉に手を貸す"},
{no:291,en:"give〈人〉a call",ja:"〈人〉に電話をする"},
{no:292,en:"give birth to ...",ja:"…を産む"},
{no:293,en:"give up (...)",ja:"（…を）あきらめる"},
{no:294,en:"give in (...)",ja:"譲る"},
{no:295,en:"give way to ...",ja:"…に譲歩する"},
{no:296,en:"given ...",ja:"…を考慮に入れれば"},
{no:297,en:"give out ...",ja:"…を配る"},
{no:298,en:"give away ...",ja:"（秘密など）を明かす"},
{no:299,en:"give rise to ...",ja:"…を引き起こす"},
{no:300,en:"give off ...",ja:"（におい・熱など）を発する"},
{no:301,en:"take care of ...",ja:"…の世話をする"},
{no:302,en:"take over (...)",ja:"（…を）引き継ぐ"},
{no:303,en:"take part in ...",ja:"…に参加する"},
{no:304,en:"it takes〈人〉〈時間〉to do",ja:"〈人〉が～するのに〈時間〉がかかる"},
{no:305,en:"take ... for granted",ja:"…をあたりまえに思う"},
{no:306,en:"take it easy",ja:"気楽にする"},
{no:307,en:"take ... for",ja:"（誤って）…を～だと思い込む"},
{no:308,en:"leave ... behind",ja:"…を置き忘れる"},
{no:309,en:"leave much to be desired",ja:"問題が多い"},
{no:310,en:"leave ... alone",ja:"…をひとりにしておく"},
{no:311,en:"leave ... out",ja:"…を省く"},
{no:312,en:"keep good hours",ja:"早寝早起きをする"},
{no:313,en:"keep a diary",ja:"日記をつける"},
{no:314,en:"keep good time",ja:"（時計の）時間が正確である"},
{no:315,en:"keep (on) -ing",ja:"～し続ける"},
{no:316,en:"keep ... -ing",ja:"…を～するままにしておく"},
{no:317,en:"keep〈人〉company",ja:"〈人〉に同行する"},
{no:318,en:"keep ～ in mind",ja:"～を覚えている"},
{no:319,en:"keep up with ～",ja:"（時勢など）に遅れずについていく"},
{no:320,en:"set out (...)",ja:"（…に）出発する"},
{no:321,en:"set in",ja:"（季節・天気が）始まる"},
{no:322,en:"set about ...",ja:"…に取りかかる"},
{no:323,en:"have a good time -ing",ja:"～して楽しむ"},
{no:324,en:"have no idea",ja:"わからない"},
{no:325,en:"have an eye for ...",ja:"…を見る目がある"},
{no:326,en:"have only to do",ja:"～しさえすればよい"},
{no:327,en:"have ... done",ja:"…を～してもらう"},
{no:328,en:"have words with ...",ja:"…と口論する"},
{no:329,en:"have an effect on ...",ja:"…に影響を与える"},
{no:330,en:"have one's own way",ja:"自分の思い通りにする"},
{no:331,en:"have a good command of ...",ja:"…を自由にあやつる"},
{no:332,en:"have no choice but to do",ja:"～せざるをえない"},
{no:333,en:"get to do",ja:"～するようになる"},
{no:334,en:"get ... to do",ja:"…に～させる"},
{no:335,en:"get ... done",ja:"…を～してしまう"},
{no:336,en:"get in touch with ...",ja:"…と連絡を取る"},
{no:337,en:"get on with ...",ja:"…と仲よくやっていく"},
{no:338,en:"get nowhere",ja:"進展しない"},
{no:339,en:"get on one's nerves",ja:"～をいらつかせる"},
{no:340,en:"get in one's way",ja:"～のじゃまをする"},
{no:341,en:"get around",ja:"あちこち移動する"},
{no:342,en:"get back to ～",ja:"（元の話題など）に戻る"},
{no:343,en:"accident",ja:"（交通）事故"},
{no:344,en:"pain",ja:"痛み"},
{no:345,en:"ill",ja:"病気で"},
{no:346,en:"die",ja:"死ぬ"},
{no:347,en:"remind",ja:"に思い出させる"},
{no:348,en:"inform",ja:"に知らせる"},
{no:349,en:"convince",ja:"に納得させる"},
{no:350,en:"warn",ja:"に警告する"},
{no:351,en:"suspect",ja:"を疑う"},
{no:352,en:"company",ja:"会社"},
{no:353,en:"project",ja:"計画"},
{no:354,en:"career",ja:"（生涯の）仕事"},
{no:355,en:"clerk",ja:"店員"},
{no:356,en:"document",ja:"文書"},
{no:357,en:"envelope",ja:"封筒"},
{no:358,en:"rob",ja:"を奪う"},
{no:359,en:"deprive",ja:"（能力・権利など）を奪う"},
{no:360,en:"cure",ja:"を治す"},
{no:361,en:"cheat",ja:"をだます"},
{no:362,en:"clear",ja:"を片づける"},
{no:363,en:"relieve",ja:"を和らげる"},
{no:364,en:"rid",ja:"を取り除く"},
{no:365,en:"act",ja:"行動する"},
{no:366,en:"consume",ja:"を消費する"},
{no:367,en:"burn",ja:"燃える"},
{no:368,en:"continue",ja:"続く"},
{no:369,en:"gather",ja:"集まる"},
{no:370,en:"include",ja:"を含む"},
{no:371,en:"spend",ja:"（お金）を費やす"},
{no:372,en:"wake",ja:"を起こす"},
{no:373,en:"prevent",ja:"を妨げる"},
{no:374,en:"keep",ja:"を妨げる"},
{no:375,en:"prohibit",ja:"を禁止する"},
{no:376,en:"discourage",ja:"にやる気をなくさせる"},
{no:377,en:"personality",ja:"個性"},
{no:378,en:"shy",ja:"恥ずかしがりの"},
{no:379,en:"brave",ja:"勇敢な"},
{no:380,en:"smart",ja:"頭のよい"},
{no:381,en:"lazy",ja:"怠惰な"},
{no:382,en:"independent",ja:"独立した"},
{no:383,en:"serve",ja:"（に）仕える"},
{no:384,en:"provide",ja:"を供給する"},
{no:385,en:"supply",ja:"を供給する"},
{no:386,en:"central",ja:"中心の"},
{no:387,en:"shape",ja:"形"},
{no:388,en:"surface",ja:"表面"},
{no:389,en:"spot",ja:"場所"},
{no:390,en:"thick",ja:"厚い"},
{no:391,en:"tight",ja:"きつい"},
{no:392,en:"rough",ja:"（表面が）でこぼこした"},
{no:393,en:"dull",ja:"（色・光・感覚などが）鈍い"},
{no:394,en:"blame",ja:"を非難する"},
{no:395,en:"praise",ja:"を賞賛する"},
{no:396,en:"criticize",ja:"を批判する"},
{no:397,en:"punish",ja:"を罰する"},
{no:398,en:"thank",ja:"に感謝する"},
{no:399,en:"alone",ja:"ひとりで"},
{no:400,en:"liable",ja:"しやすい"},
{no:401,en:"home",ja:"わが家へ（に）"},
{no:402,en:"indeed",ja:"たしかに"},
{no:403,en:"relatively",ja:"比較的"},
{no:404,en:"respectively",ja:"それぞれに"},
{no:405,en:"ever",ja:"かつて"},
{no:406,en:"badly",ja:"ひどく"},
{no:407,en:"first",ja:"まず最初に"},
{no:408,en:"take",ja:"を取る"},
{no:409,en:"bring",ja:"を持ってくる"},
{no:410,en:"traffic",ja:"交通"},
{no:411,en:"transportation",ja:"輸送機関"},
{no:412,en:"path",ja:"小道"},
{no:413,en:"fuel",ja:"燃料"},
{no:414,en:"move",ja:"動く"},
{no:415,en:"cross",ja:"（を）横切る"},
{no:416,en:"return",ja:"戻る"},
{no:417,en:"turn",ja:"回る"},
{no:418,en:"spread",ja:"広がる"},
{no:419,en:"hurry",ja:"急ぐ"},
{no:420,en:"ride",ja:"（車など）に乗る"},
{no:421,en:"impression",ja:"印象"},
{no:422,en:"image",ja:"イメージ"},
{no:423,en:"personal",ja:"個人的な"},
{no:424,en:"private",ja:"私用の"},
{no:425,en:"individual",ja:"個々の"},
{no:426,en:"celebrate",ja:"（を）祝う"},
{no:427,en:"nod",ja:"うなずく"},
{no:428,en:"pardon",ja:"を許す"},
{no:429,en:"please",ja:"を喜ばせる"},
{no:430,en:"worry",ja:"心配する"},
{no:431,en:"wish",ja:"（を）望む"},
{no:432,en:"depend",ja:"…に頼る"},
{no:433,en:"rely",ja:"…に頼る"},
{no:434,en:"minute",ja:"分"},
{no:435,en:"moment",ja:"瞬間"},
{no:436,en:"rapid",ja:"速い"},
{no:437,en:"brief",ja:"短時間の"},
{no:438,en:"immediately",ja:"ただちに"},
{no:439,en:"current",ja:"現在の"},
{no:440,en:"instantly",ja:"すぐに"},
{no:441,en:"repeat",ja:"（を）くり返す"},
{no:442,en:"whisper",ja:"（を）ささやく"},
{no:443,en:"pronounce",ja:"（を）発音する"},
{no:444,en:"excuse",ja:"を許す"},
{no:445,en:"literature",ja:"文学（作品）"},
{no:446,en:"novel",ja:"小説"},
{no:447,en:"sentence",ja:"文"},
{no:448,en:"content",ja:"内容"},
{no:449,en:"author",ja:"著者"},
{no:450,en:"judge",ja:"（を）判断する"},
{no:451,en:"solve",ja:"（問題）を解く"},
{no:452,en:"prove",ja:"を証明する"},
{no:453,en:"notice",ja:"に気づく"},
{no:454,en:"realize",ja:"に気づく"},
{no:455,en:"check",ja:"（を）調べる"},
{no:456,en:"explain",ja:"（を）説明する"},
{no:457,en:"imagine",ja:"（を）想像する"},
{no:458,en:"adjust",ja:"を調整する"},
{no:459,en:"expert",ja:"専門家"},
{no:460,en:"professor",ja:"教授"},
{no:461,en:"instruction",ja:"指導"},
{no:462,en:"survey",ja:"調査"},
{no:463,en:"grade",ja:"成績"},
{no:464,en:"major",ja:"専攻する"},
{no:465,en:"appeal",ja:"（世論・武力などに）訴える"},
{no:466,en:"communicate",ja:"を伝える"},
{no:467,en:"introduce",ja:"を紹介する"},
{no:468,en:"react",ja:"反応する"},
{no:469,en:"respond",ja:"（に）対応する"},
{no:470,en:"support",ja:"を支える"},
{no:471,en:"treat",ja:"を扱う"},
{no:472,en:"size",ja:"大きさ"},
{no:473,en:"fat",ja:"太った"},
{no:474,en:"bare",ja:"裸の"},
{no:475,en:"advise",ja:"（に）忠告する"},
{no:476,en:"decide",ja:"を決める"},
{no:477,en:"demand",ja:"を要求する"},
{no:478,en:"insist",ja:"（と）主張する"},
{no:479,en:"forbid",ja:"を禁止する"},
{no:480,en:"propose",ja:"を提案する"},
{no:481,en:"request",ja:"を要請する"},
{no:482,en:"suggest",ja:"を提案する"},
{no:483,en:"origin",ja:"起源"},
{no:484,en:"civilization",ja:"文明"},
{no:485,en:"race",ja:"人種"},
{no:486,en:"progress",ja:"進歩"},
{no:487,en:"event",ja:"できごと"},
{no:488,en:"adventure",ja:"冒険"},
{no:489,en:"treasure",ja:"宝物"},
{no:490,en:"crop",ja:"農作物"},
{no:491,en:"harvest",ja:"収穫"},
{no:492,en:"sew",ja:"を縫う"},
{no:493,en:"receive",ja:"を受け取る"},
{no:494,en:"bend",ja:"を曲げる"},
{no:495,en:"collect",ja:"を集める"},
{no:496,en:"fix",ja:"を修理する"},
{no:497,en:"grab",ja:"をつかむ"},
{no:498,en:"excellent",ja:"優れた"},
{no:499,en:"essential",ja:"不可欠の"},
{no:500,en:"proper",ja:"適切な"},
{no:501,en:"worth",ja:"～の価値がある"},
{no:502,en:"severe",ja:"（人・規律が）厳しい"},
{no:503,en:"awful",ja:"ひどい"},
{no:504,en:"evil",ja:"邪悪な"},
{no:505,en:"ugly",ja:"みにくい"},
{no:506,en:"increase",ja:"増える"},
{no:507,en:"reduce",ja:"を減らす"},
{no:508,en:"lose",ja:"を失う"},
{no:509,en:"produce",ja:"を生産する"},
{no:510,en:"period",ja:"期間"},
{no:511,en:"former",ja:"前の"},
{no:512,en:"latter",ja:"あとの"},
{no:513,en:"modern",ja:"現代の"},
{no:514,en:"ancient",ja:"古代の"},
{no:515,en:"afterward(s)",ja:"あとで"},
{no:516,en:"tell",ja:"（を）話す"},
{no:517,en:"say",ja:"…と言う"},
{no:518,en:"speak",ja:"話す"},
{no:519,en:"talk",ja:"話す"},
{no:520,en:"complete",ja:"完全な"},
{no:521,en:"ideal",ja:"理想的な"},
{no:522,en:"complex",ja:"複雑な"},
{no:523,en:"general",ja:"概略の"},
{no:524,en:"plain",ja:"明らかな"},
{no:525,en:"available",ja:"利用できる"},
{no:526,en:"fortunately",ja:"幸運にも"},
{no:527,en:"borrow",ja:"（無料で）を借りる"},
{no:528,en:"rent",ja:"（土地・家など）を賃借りする"},
{no:529,en:"exchange",ja:"を交換する"},
{no:530,en:"lend",ja:"（もの・金）を貸す"},
{no:531,en:"fashion",ja:"流行"},
{no:532,en:"crowd",ja:"群衆"},
{no:533,en:"avenue",ja:"大通り"},
{no:534,en:"suburb",ja:"郊外"},
{no:535,en:"local",ja:"地元の"},
{no:536,en:"suppose",ja:"…と思う"},
{no:537,en:"associate",ja:"…で～を連想する"},
{no:538,en:"regard",ja:"…を～とみなす"},
{no:539,en:"wonder",ja:"～だろうかと思う"},
{no:540,en:"determine",ja:"を決心する"},
{no:541,en:"identify",ja:"が誰（何）だかわかる"},
{no:542,en:"wrap",ja:"を包む"},
{no:543,en:"press",ja:"（を）押す"},
{no:544,en:"polish",ja:"をみがく"},
{no:545,en:"pack",ja:"を詰め込む"},
{no:546,en:"mend",ja:"を修繕する"},
{no:547,en:"hang",ja:"を掛ける"},
{no:548,en:"excite",ja:"を興奮させる"},
{no:549,en:"exciting",ja:"興奮させる"},
{no:550,en:"excited",ja:"（人が）興奮した"},
{no:551,en:"fasten",ja:"を固定する"},
{no:552,en:"fold",ja:"を折りたたむ"},
{no:553,en:"pour",ja:"（液体など）を注ぐ"},
{no:554,en:"fit",ja:"（に）合う"},
{no:555,en:"care",ja:"を気にかける"},
{no:556,en:"interest",ja:"に興味を持たせる"},
{no:557,en:"interesting",ja:"興味深い"},
{no:558,en:"interested",ja:"（人が）興味を持った"},
{no:559,en:"satisfy",ja:"を満足させる"},
{no:560,en:"satisfying",ja:"満足のいく"},
{no:561,en:"satisfied",ja:"（人が）満足した"},
{no:562,en:"tire",ja:"を疲れさせる"},
{no:563,en:"tiring",ja:"疲れる"},
{no:564,en:"tired",ja:"（人が）疲れた"},
{no:565,en:"occur",ja:"起こる"},
{no:566,en:"quit",ja:"（を）やめる"},
{no:567,en:"retire",ja:"退職する"},
{no:568,en:"settle",ja:"（紛争・問題など）を解決する"},
{no:569,en:"amaze",ja:"をびっくりさせる"},
{no:570,en:"amazing",ja:"びっくりするような"},
{no:571,en:"amazed",ja:"（人が）びっくりした"},
{no:572,en:"amuse",ja:"をおもしろがらせる"},
{no:573,en:"amusing",ja:"おもしろい"},
{no:574,en:"amused",ja:"（人が）おもしろがって"},
{no:575,en:"bore",ja:"を退屈させる"},
{no:576,en:"boring",ja:"退屈な"},
{no:577,en:"bored",ja:"（人が）退屈した"},
{no:578,en:"religion",ja:"宗教"},
{no:579,en:"soul",ja:"魂"},
{no:580,en:"miracle",ja:"奇跡"},
{no:581,en:"ghost",ja:"幽霊"},
{no:582,en:"spirit",ja:"精神"},
{no:583,en:"annoy",ja:"をいらいらさせる"},
{no:584,en:"annoying",ja:"いらいらさせる"},
{no:585,en:"annoyed",ja:"（人が）いらいらした"},
{no:586,en:"confuse",ja:"を混乱させる"},
{no:587,en:"confusing",ja:"混乱させるような"},
{no:588,en:"confused",ja:"（人が）混乱した"},
{no:589,en:"disappoint",ja:"を失望させる"},
{no:590,en:"disappointing",ja:"失望させる"},
{no:591,en:"disappointed",ja:"（人が）失望した"},
{no:592,en:"furious",ja:"激怒した"},
{no:593,en:"glad",ja:"うれしい"},
{no:594,en:"happy",ja:"幸福な"},
{no:595,en:"sorry",ja:"気の毒で"},
{no:596,en:"thankful",ja:"感謝して"},
{no:597,en:"shock",ja:"に衝撃を与える"},
{no:598,en:"shocking",ja:"ぞっとするような"},
{no:599,en:"shocked",ja:"衝撃を受けた"},
{no:600,en:"surprise",ja:"を驚かせる"},
{no:601,en:"surprising",ja:"驚くべき"},
{no:602,en:"surprised",ja:"驚いて"},
{no:603,en:"ocean",ja:"海"},
{no:604,en:"palm",ja:"ヤシ"},
{no:605,en:"coral",ja:"サンゴ"},
{no:606,en:"reef",ja:"礁"},
{no:607,en:"cave",ja:"洞くつ"},
{no:608,en:"advantage",ja:"利点"},
{no:609,en:"bond",ja:"接着（剤）"},
{no:610,en:"identity",ja:"身元"},
{no:611,en:"impact",ja:"強い影響（力）"},
{no:612,en:"sight",ja:"光景"},
{no:613,en:"site",ja:"場所"},
{no:614,en:"sort",ja:"種類"},
{no:615,en:"tip",ja:"秘訣"},
{no:616,en:"version",ja:"型"},
{no:617,en:"make a difference",ja:"変化をもたらす"},
{no:618,en:"make the best of ...",ja:"（悪い状況など）を最大限に活用する"},
{no:619,en:"make use of ...",ja:"…を利用する"},
{no:620,en:"make sure (of) ...",ja:"…を確かめる"},
{no:621,en:"make up with ...",ja:"…と仲直りをする"},
{no:622,en:"make out ...",ja:"…を理解する"},
{no:623,en:"make it impossible for〈人〉to do",ja:"〈人〉が～するのを不可能にする"},
{no:624,en:"help〈人〉with ...",ja:"〈人〉の…を手伝う"},
{no:625,en:"help ... (to) do",ja:"…が～するのを手伝う"},
{no:626,en:"cannot help -ing",ja:"～せずにはいられない"},
{no:627,en:"help (...) out",ja:"（…を）手伝う"},
{no:628,en:"come up with ...",ja:"（考えなど）を思いつく"},
{no:629,en:"come into being",ja:"（ものが）誕生する"},
{no:630,en:"come about",ja:"（ことが）起こる"},
{no:631,en:"come up",ja:"（問題などが）生じる"},
{no:632,en:"come out",ja:"（太陽・月など）が現れる"},
{no:633,en:"come into effect",ja:"（法律などが）施行される"},
{no:634,en:"stand by (...)",ja:"…を支える"},
{no:635,en:"stand up for ...",ja:"…を支持する"},
{no:636,en:"stand for ...",ja:"…を表す"},
{no:637,en:"stand out",ja:"目立つ"},
{no:638,en:"take after ...",ja:"…に似ている"},
{no:639,en:"take up ...",ja:"…を始める"},
{no:640,en:"take place",ja:"（式・行事などが）行われる"},
{no:641,en:"take one's time on ...",ja:"…をゆっくりやる"},
{no:642,en:"take in ...",ja:"（客など）を受け入れる"},
{no:643,en:"take ... into account",ja:"…を考慮に入れる"},
{no:644,en:"take ... into consideration",ja:"…を考慮に入れる"},
{no:645,en:"take on ...",ja:"…を引き受ける"},
{no:646,en:"bring out ...",ja:"（製品など）を出す"},
{no:647,en:"bring oneself to do",ja:"～する気になる"},
{no:648,en:"bring ... to light",ja:"（証拠など）を明るみに出す"},
{no:649,en:"bring ... home to〈人〉",ja:"〈人〉に…を痛感させる"},
{no:650,en:"bring ... up",ja:"…を育てる"},
{no:651,en:"keep ... from -ing",ja:"…が～するのを妨げる"},
{no:652,en:"keep away from ...",ja:"…に近づかない"},
{no:653,en:"keep in touch with ...",ja:"…と連絡を取り合う"},
{no:654,en:"keep ... to oneself",ja:"…を人に話さないでおく"},
{no:655,en:"keep off ...",ja:"…に立ち入らない"},
{no:656,en:"keep to ...",ja:"（規則など）に従う"},
{no:657,en:"keep one's word",ja:"約束を守る"},
{no:658,en:"keep an eye on ...",ja:"…を見張る"},
{no:659,en:"turn up",ja:"現れる"},
{no:660,en:"turn out (to be) ...",ja:"…だとわかる"},
{no:661,en:"turn down ...",ja:"…を断る"},
{no:662,en:"by turns",ja:"代わる代わるに"},
{no:663,en:"in turn",ja:"順番に"},
{no:664,en:"get down to ...",ja:"…に取りかかる"},
{no:665,en:"get over ...",ja:"…を乗り越える"},
{no:666,en:"get the better of ...",ja:"…に勝つ"},
{no:667,en:"get rid of ...",ja:"…を取り除く"},
{no:668,en:"get through ...",ja:"…を終える"},
{no:669,en:"get at ...",ja:"…を言おうとする"},
{no:670,en:"hold the line",ja:"電話を切らないでおく"},
{no:671,en:"hold one's breath",ja:"息を止める"},
{no:672,en:"hold one's tongue",ja:"黙っている"},
{no:673,en:"hold good",ja:"有効である"},
{no:674,en:"hold out (...)",ja:"（攻撃などに）耐える"},
{no:675,en:"hold back ...",ja:"…を押しとどめる"},
{no:676,en:"let ... alone",ja:"…をそのままにしておく"},
{no:677,en:"let alone ...",ja:"…は言うまでもなく"},
{no:678,en:"let ... down",ja:"…をがっかりさせる"},
{no:679,en:"let ... out",ja:"（秘密など）をもらす"},
{no:680,en:"let go of one's hand",ja:"～の手を放す"},
{no:681,en:"do over ...",ja:"…をやり直す"},
{no:682,en:"do nothing but",ja:"～してばかりいる"},
{no:683,en:"do with ...",ja:"…で間に合わせる"},
{no:684,en:"do without ...",ja:"…なしですます"},
{no:685,en:"do ... good",ja:"…に益をもたらす"},
{no:686,en:"any ... will do",ja:"どんな…でも役に立つ"},
{no:687,en:"do away with ...",ja:"…を廃止する"},
{no:688,en:"call (...) up",ja:"（…に）電話をする"},
{no:689,en:"call for ...",ja:"…を強く求める"},
{no:690,en:"call on〈人〉",ja:"〈人〉を訪問する"},
{no:691,en:"call it a day",ja:"（その日の）仕事を切り上げる"},
{no:692,en:"call (...) back",ja:"（…に）折り返し電話する"},
{no:693,en:"call ... off",ja:"…を中止する"},
{no:694,en:"call in",ja:"電話を入れる"},
{no:695,en:"put an end to ...",ja:"…を終わらせる"},
{no:696,en:"put up with ...",ja:"…をがまんする"},
{no:697,en:"put on ...",ja:"（服など）を着る"},
{no:698,en:"put off ...",ja:"…を延期する"},
{no:699,en:"put forward ...",ja:"（意見・提案など）を出す"},
{no:700,en:"technique",ja:"（専門）技術"},
{no:701,en:"method",ja:"方法"},
{no:702,en:"manufacture",ja:"製造"},
{no:703,en:"harm",ja:"に害を与える"},
{no:704,en:"suffer",ja:"苦しむ"},
{no:705,en:"hurt",ja:"を傷つける"},
{no:706,en:"injure",ja:"にけがをさせる"},
{no:707,en:"crash",ja:"（車が）衝突する"},
{no:708,en:"destroy",ja:"を破壊する"},
{no:709,en:"ruin",ja:"を台なしにする"},
{no:710,en:"explode",ja:"爆発する"},
{no:711,en:"shoot",ja:"（を）撃つ"},
{no:712,en:"recover",ja:"回復する"},
{no:713,en:"volcano",ja:"火山"},
{no:714,en:"dust",ja:"ほこり"},
{no:715,en:"soil",ja:"土"},
{no:716,en:"solar",ja:"太陽の"},
{no:717,en:"jewel",ja:"宝石"},
{no:718,en:"agriculture",ja:"農業"},
{no:719,en:"grain",ja:"穀物"},
{no:720,en:"dessert",ja:"デザート"},
{no:721,en:"raw",ja:"（食べ物が）生の"},
{no:722,en:"shrimp",ja:"（小）エビ"},
{no:723,en:"bake",ja:"（パンなど）を焼く"},
{no:724,en:"boil",ja:"を沸騰させる"},
{no:725,en:"melt",ja:"を溶かす"},
{no:726,en:"feed",ja:"にえさをあげる"},
{no:727,en:"blood",ja:"血"},
{no:728,en:"breath",ja:"息"},
{no:729,en:"birth",ja:"誕生"},
{no:730,en:"disease",ja:"病気"},
{no:731,en:"fever",ja:"（病気の）熱"},
{no:732,en:"cough",ja:"せき"},
{no:733,en:"aid",ja:"手当"},
{no:734,en:"pale",ja:"青ざめた"},
{no:735,en:"comfortable",ja:"快適な"},
{no:736,en:"asleep",ja:"眠って"},
{no:737,en:"hardly",ja:"ほとんど～ない"},
{no:738,en:"scarcely",ja:"ほとんど～ない"},
{no:739,en:"rarely",ja:"めったに～ない"},
{no:740,en:"seldom",ja:"めったに～ない"},
{no:741,en:"government",ja:"政府"},
{no:742,en:"politics",ja:"政治（学）"},
{no:743,en:"policy",ja:"政策"},
{no:744,en:"democracy",ja:"民主主義"},
{no:745,en:"system",ja:"制度"},
{no:746,en:"president",ja:"大統領"},
{no:747,en:"citizen",ja:"市民"},
{no:748,en:"official",ja:"公式の"},
{no:749,en:"doubt",ja:"…ではないと思う"},
{no:750,en:"write",ja:"（文字など）を書く"},
{no:751,en:"draw",ja:"（線で絵や図形など）を描く"},
{no:752,en:"challenge",ja:"に異議を唱える"},
{no:753,en:"achieve",ja:"を達成する"},
{no:754,en:"struggle",ja:"闘う"},
{no:755,en:"chase",ja:"を追跡する"},
{no:756,en:"careless",ja:"不注意な"},
{no:757,en:"wise",ja:"賢明な"},
{no:758,en:"foolish",ja:"愚かな"},
{no:759,en:"clever",ja:"利口な"},
{no:760,en:"stupid",ja:"ばかな"},
{no:761,en:"kind",ja:"親切な"},
{no:762,en:"considerate",ja:"思いやりがある"},
{no:763,en:"polite",ja:"礼儀正しい"},
{no:764,en:"rude",ja:"失礼な"},
{no:765,en:"cruel",ja:"残酷な"},
{no:766,en:"frequently",ja:"頻繁に"},
{no:767,en:"occasionally",ja:"たまに"},
{no:768,en:"gradually",ja:"だんだんと"},
{no:769,en:"finally",ja:"ようやく"},
{no:770,en:"exercise",ja:"運動する"},
{no:771,en:"operate",ja:"（機械など）を操作する"},
{no:772,en:"bow",ja:"おじぎをする"},
{no:773,en:"lift",ja:"を持ち上げる"},
{no:774,en:"row",ja:"ボートをこぐ"},
{no:775,en:"roll",ja:"転がる"},
{no:776,en:"float",ja:"浮かぶ"},
{no:777,en:"eliminate",ja:"を削除する"},
{no:778,en:"perform",ja:"（を）演じる"},
{no:779,en:"confidence",ja:"信頼"},
{no:780,en:"effort",ja:"努力"},
{no:781,en:"favor",ja:"好意"},
{no:782,en:"responsible",ja:"責任のある"},
{no:783,en:"serious",ja:"真剣な"},
{no:784,en:"curious",ja:"好奇心の強い"},
{no:785,en:"aggressive",ja:"攻撃的な"},
{no:786,en:"fear",ja:"恐れ"},
{no:787,en:"superior",ja:"優れた"},
{no:788,en:"inferior",ja:"劣った"},
{no:789,en:"senior",ja:"年上の"},
{no:790,en:"junior",ja:"年下の"},
{no:791,en:"prefer",ja:"を好む"},
{no:792,en:"thief",ja:"どろぼう"},
{no:793,en:"crime",ja:"（法律上の）罪"},
{no:794,en:"battle",ja:"（局地的な）戦闘"},
{no:795,en:"weapon",ja:"武器"},
{no:796,en:"enemy",ja:"敵"},
{no:797,en:"alarm",ja:"警報（器）"},
{no:798,en:"guilty",ja:"有罪の"},
{no:799,en:"outbreak",ja:"（悪いことの）勃発"},
{no:800,en:"rush",ja:"突進する"},
{no:801,en:"pity",ja:"あわれみ"},
{no:802,en:"dislike",ja:"をいやがる"},
{no:803,en:"hesitate",ja:"をためらう"},
{no:804,en:"lead",ja:"を導く"},
{no:805,en:"conduct",ja:"を行う"},
{no:806,en:"direct",ja:"を向ける"},
{no:807,en:"influence",ja:"に影響を与える"},
{no:808,en:"affect",ja:"に（直接的な）影響を与える"},
{no:809,en:"exert",ja:"（力・影響力など）を使う"},
{no:810,en:"favorite",ja:"お気に入りの"},
{no:811,en:"favorable",ja:"（返事などが）好意的な"},
{no:812,en:"industrial",ja:"産業の"},
{no:813,en:"industrious",ja:"勤勉な"},
{no:814,en:"sensitive",ja:"敏感な"},
{no:815,en:"sensible",ja:"分別のある"},
{no:816,en:"display",ja:"を陳列する"},
{no:817,en:"arrange",ja:"を手配する"},
{no:818,en:"imitate",ja:"をまねる"},
{no:819,en:"indicate",ja:"を示す"},
{no:820,en:"behave",ja:"ふるまう"},
{no:821,en:"attract",ja:"を引きつける"},
{no:822,en:"entertain",ja:"を楽しませる"},
{no:823,en:"successful",ja:"成功した"},
{no:824,en:"successive",ja:"連続の"},
{no:825,en:"literate",ja:"読み書きができる"},
{no:826,en:"literal",ja:"文字どおりの"},
{no:827,en:"literary",ja:"文学の"},
{no:828,en:"healthful",ja:"健康によい"},
{no:829,en:"healthy",ja:"健康な"},
{no:830,en:"invaluable",ja:"非常に価値のある"},
{no:831,en:"valueless",ja:"価値のない"},
{no:832,en:"social",ja:"社会の"},
{no:833,en:"sociable",ja:"社交的な"},
{no:834,en:"minor",ja:"（程度が）小さな"},
{no:835,en:"collective",ja:"集団の"},
{no:836,en:"overall",ja:"全体の"},
{no:837,en:"internal",ja:"内（部）の"},
{no:838,en:"commonly",ja:"一般に"},
{no:839,en:"totally",ja:"まったく"},
{no:840,en:"eventually",ja:"最後には"},
{no:841,en:"primarily",ja:"おもに"},
{no:842,en:"alike",ja:"似ている"},
{no:843,en:"similar",ja:"同類の"},
{no:844,en:"equal",ja:"等しい"},
{no:845,en:"variety",ja:"種類"},
{no:846,en:"state",ja:"を（はっきり）述べる"},
{no:847,en:"refer",ja:"言及する"},
{no:848,en:"claim",ja:"を主張する"},
{no:849,en:"approve",ja:"（に）賛成する"},
{no:850,en:"recommend",ja:"を勧める"},
{no:851,en:"reply",ja:"返事をする"},
{no:852,en:"correct",ja:"を訂正する／正しい"},
{no:853,en:"accept",ja:"を受け入れる"},
{no:854,en:"debate",ja:"を討論する"},
{no:855,en:"despite",ja:"～にもかかわらず"},
{no:856,en:"beyond",ja:"～を越えて"},
{no:857,en:"beneath",ja:"～の下に"},
{no:858,en:"besides",ja:"～のほかに"},
{no:859,en:"throughout",ja:"～のいたるところに"},
{no:860,en:"therefore",ja:"したがって"},
{no:861,en:"anyway",ja:"とにかく"},
{no:862,en:"high",ja:"（高さ・位置が）高い"},
{no:863,en:"low",ja:"（高さ・位置が）低い"},
{no:864,en:"expensive",ja:"（品物が）高価な"},
{no:865,en:"cheap",ja:"（品物が）安い"},
{no:866,en:"large",ja:"（数・量が）多い"},
{no:867,en:"small",ja:"（数・量が）少ない"},
{no:868,en:"majority",ja:"大多数"},
{no:869,en:"minority",ja:"少数派"},
{no:870,en:"estimate",ja:"（を）見積もる"},
{no:871,en:"measure",ja:"（を）測定する"},
{no:872,en:"divide",ja:"を分ける"},
{no:873,en:"add",ja:"（を）足す"},
{no:874,en:"amount",ja:"（合計して）…に達する"},
{no:875,en:"dimension",ja:"寸法"},
{no:876,en:"able",ja:"できる"},
{no:877,en:"capable",ja:"能力がある"},
{no:878,en:"possible",ja:"可能な"},
{no:879,en:"attitude",ja:"態度"},
{no:880,en:"manner",ja:"方法"},
{no:881,en:"habit",ja:"（個人の）習慣"},
{no:882,en:"appointment",ja:"（面会の）約束"},
{no:883,en:"concern",ja:"関心"},
{no:884,en:"affair",ja:"情勢"},
{no:885,en:"consensus",ja:"意見の一致"},
{no:886,en:"announce",ja:"を公表する"},
{no:887,en:"greet",ja:"にあいさつをする"},
{no:888,en:"scold",ja:"（を）しかる"},
{no:889,en:"scream",ja:"悲鳴を上げる"},
{no:890,en:"quarrel",ja:"口論"},
{no:891,en:"breathe",ja:"呼吸する"},
{no:892,en:"sigh",ja:"ため息をつく"},
{no:893,en:"normal",ja:"標準的な"},
{no:894,en:"ordinary",ja:"ふつうの"},
{no:895,en:"average",ja:"平均的な"},
{no:896,en:"regular",ja:"規則的な"},
{no:897,en:"rare",ja:"まれな"},
{no:898,en:"particular",ja:"特定の"},
{no:899,en:"relative",ja:"相対的な"},
{no:900,en:"publish",ja:"（を）出版する"},
{no:901,en:"print",ja:"（を）印刷する"},
{no:902,en:"broadcast",ja:"を放送する"},
{no:903,en:"create",ja:"を創作する"},
{no:904,en:"design",ja:"を設計する"},
{no:905,en:"media",ja:"（マス）メディア"},
{no:906,en:"murder",ja:"殺人（事件）"},
{no:907,en:"arrest",ja:"を逮捕する"},
{no:908,en:"seize",ja:"を押収する"},
{no:909,en:"surround",ja:"を囲む"},
{no:910,en:"oppress",ja:"を虐げる"},
{no:911,en:"trigger",ja:"引き金"},
{no:912,en:"dangerous",ja:"危険な"},
{no:913,en:"useless",ja:"むだな"},
{no:914,en:"impossible",ja:"不可能な"},
{no:915,en:"convenient",ja:"便利な"},
{no:916,en:"necessary",ja:"必要な"},
{no:917,en:"topic",ja:"話題"},
{no:918,en:"direction",ja:"指揮"},
{no:919,en:"result",ja:"結果"},
{no:920,en:"conclusion",ja:"結論"},
{no:921,en:"opportunity",ja:"機会"},
{no:922,en:"principal",ja:"おもな"},
{no:923,en:"opposite",ja:"正反対の"},
{no:924,en:"poll",ja:"世論調査"},
{no:925,en:"admire",ja:"に感心する"},
{no:926,en:"anticipate",ja:"を予想する"},
{no:927,en:"contradict",ja:"と矛盾する"},
{no:928,en:"distract",ja:"（注意など）をそらす"},
{no:929,en:"board",ja:"委員会"},
{no:930,en:"committee",ja:"委員会"},
{no:931,en:"statement",ja:"声明"},
{no:932,en:"strategy",ja:"戦略"},
{no:933,en:"gain",ja:"を得る"},
{no:934,en:"obtain",ja:"を手に入れる"},
{no:935,en:"score",ja:"（得点・点数）を取る"},
{no:936,en:"lack",ja:"を欠く"},
{no:937,en:"decrease",ja:"減る"},
{no:938,en:"replace",ja:"に取ってかわる"},
{no:939,en:"remove",ja:"を取り去る"},
{no:940,en:"adopt",ja:"を採用する"},
{no:941,en:"stare",ja:"（を）じっと見る"},
{no:942,en:"discover",ja:"を発見する"},
{no:943,en:"seek",ja:"（を）捜す"},
{no:944,en:"search",ja:"（場所）を捜す"},
{no:945,en:"recognize",ja:"が誰（何）だかわかる"},
{no:946,en:"advice",ja:"忠告"},
{no:947,en:"baggage",ja:"（旅行の）手荷物"},
{no:948,en:"furniture",ja:"家具"},
{no:949,en:"information",ja:"情報"},
{no:950,en:"machinery",ja:"機械装置"},
{no:951,en:"news",ja:"報道"},
{no:952,en:"access",ja:"接近"},
{no:953,en:"flock",ja:"（鳥や羊の）群れ"},
{no:954,en:"herd",ja:"（牛や馬の）群れ"},
{no:955,en:"school",ja:"（魚の）群れ"},
{no:956,en:"shade",ja:"（日）陰"},
{no:957,en:"shadow",ja:"影"},
{no:958,en:"dentist",ja:"歯科医"},
{no:959,en:"surgeon",ja:"外科医"},
{no:960,en:"physician",ja:"医者"},
{no:961,en:"repair",ja:"を修理する"},
{no:962,en:"restore",ja:"を修復する"},
{no:963,en:"homework",ja:"宿題"},
{no:964,en:"housework",ja:"家事"},
{no:965,en:"poetry",ja:"詩"},
{no:966,en:"scenery",ja:"風景"},
{no:967,en:"fun",ja:"楽しみ"},
{no:968,en:"economy",ja:"経済（活動）"},
{no:969,en:"price",ja:"価格"},
{no:970,en:"trade",ja:"貿易"},
{no:971,en:"industry",ja:"産業"},
{no:972,en:"loss",ja:"損失"},
{no:973,en:"consumer",ja:"消費者"},
{no:974,en:"duty",ja:"関税"},
{no:975,en:"balance",ja:"（預金などの）残高"},
{no:976,en:"guarantee",ja:"を保証する"},
{no:977,en:"join",ja:"（人や団体）に加わる"},
{no:978,en:"participate",ja:"（活動）に参加する"},
{no:979,en:"organize",ja:"（行事・活動など）を準備する"},
{no:980,en:"unite",ja:"団結する"},
{no:981,en:"make oneself understood",ja:"自分の意思を伝える"},
{no:982,en:"make a living",ja:"生計を立てる"},
{no:983,en:"make way for ...",ja:"…に道を譲る"},
{no:984,en:"make one's way",ja:"（やっとのことで）進む"},
{no:985,en:"make for ...",ja:"…のほうへ向かう"},
{no:986,en:"make oneself at home",ja:"気楽にする"},
{no:987,en:"make friends with ...",ja:"…と友だちになる"},
{no:988,en:"make fun of ...",ja:"…をからかう"},
{no:989,en:"make up ...",ja:"…をでっちあげる"},
{no:990,en:"make up for ...",ja:"…の埋め合わせをする"},
{no:991,en:"make allowance(s) for ...",ja:"…を考慮に入れる"},
{no:992,en:"make it a rule to do",ja:"～することにしている"},
{no:993,en:"look〈人〉in the face",ja:"〈人〉の顔をじっと見る"},
{no:994,en:"look like ...",ja:"…に似ている"},
{no:995,en:"look ... up in ～",ja:"…を～で調べる"},
{no:996,en:"look into ...",ja:"…を調査する"},
{no:997,en:"look ... over",ja:"…にざっと目を通す"},
{no:998,en:"look up to ...",ja:"…を尊敬する"},
{no:999,en:"look down on ...",ja:"…を見下す"},
{no:1000,en:"look on ... as ～",ja:"…を～とみなす"},
{no:1001,en:"look out for ...",ja:"…に気をつける"},
{no:1002,en:"look back on ...",ja:"…を回想する"},
{no:1003,en:"based on ～",ja:"～に基づいて"},
{no:1004,en:"break out",ja:"（戦争などが）起こる"},
{no:1005,en:"carry on (～)",ja:"（～を）続ける"},
{no:1006,en:"carry out ...",ja:"…を実行する"},
{no:1007,en:"catch up with ～",ja:"～に追いつく"},
{no:1008,en:"fill out ...",ja:"（用紙など）に記入する"},
{no:1009,en:"tell ... from ～",ja:"…を～と見分ける"},
{no:1010,en:"tell ... off",ja:"…をしかる"},
{no:1011,en:"feel free to do",ja:"自由に～する"},
{no:1012,en:"feel ill at ease",ja:"落ち着かない感じがする"},
{no:1013,en:"show up",ja:"現れる"},
{no:1014,en:"hand in ...",ja:"…を提出する"},
{no:1015,en:"learn to do",ja:"～ができるようになる"},
{no:1016,en:"think over ...",ja:"…をじっくり考える"},
{no:1017,en:"every time ...",ja:"…するときはいつも"},
{no:1018,en:"one after another",ja:"次々と"},
{no:1019,en:"on end",ja:"連続して"},
{no:1020,en:"more often than not",ja:"たいてい"},
{no:1021,en:"on and off",ja:"断続的に"},
{no:1022,en:"once in a while",ja:"ときどき"},
{no:1023,en:"once (and) for all",ja:"きっぱりと"},
{no:1024,en:"in the long run",ja:"長い目で見れば"},
{no:1025,en:"as soon as ...",ja:"…するとすぐに"},
{no:1026,en:"the moment ...",ja:"…するとすぐに"},
{no:1027,en:"no sooner ... than ～",ja:"…すると同時に～"},
{no:1028,en:"hardly ... when ～",ja:"…すると同時に～"},
{no:1029,en:"directly ...",ja:"…するとすぐに"},
{no:1030,en:"both A and B",ja:"AもBも"},
{no:1031,en:"not A but B",ja:"AでなくB"},
{no:1032,en:"not only A but also B",ja:"AだけでなくBもまた"},
{no:1033,en:"either A or B",ja:"AかBのどちらか"},
{no:1034,en:"neither A nor B",ja:"AもBも～ない"},
{no:1035,en:"so that ...",ja:"…するために"},
{no:1036,en:"in order that ...",ja:"…するために"},
{no:1037,en:"for fear (that) ...",ja:"…しないように"},
{no:1038,en:"in case ...",ja:"…するといけないから"},
{no:1039,en:"have nothing to do with ...",ja:"…とは関係がない"},
{no:1040,en:"for nothing",ja:"むだに"},
{no:1041,en:"nothing but ...",ja:"…しかない"},
{no:1042,en:"something is wrong with ...",ja:"…の調子が悪い"},
{no:1043,en:"think nothing of ...",ja:"…を何とも思わない"},
{no:1044,en:"too ... to do",ja:"～するには…すぎる"},
{no:1045,en:"... enough to do",ja:"～するのに十分…"},
{no:1046,en:"so ... as to do",ja:"～するほどに…"},
{no:1047,en:"in order to do",ja:"～するために"},
{no:1048,en:"in order not to do",ja:"～しないように"},
{no:1049,en:"so as to do",ja:"～するために"},
{no:1050,en:"so as not to do",ja:"～しないように"},
{no:1051,en:"be to do",ja:"～することになっている"},
{no:1052,en:"for the life of me",ja:"どうしても～ない"},
{no:1053,en:"under no circumstances",ja:"どんな状況でも～ない"},
{no:1054,en:"seldom, if ever",ja:"めったに～ない"},
{no:1055,en:"out of the question",ja:"論外で"},
{no:1056,en:"if one can help it",ja:"できることなら"},
{no:1057,en:"generally speaking",ja:"一般的に言えば"},
{no:1058,en:"speaking of ...",ja:"…と言えば"},
{no:1059,en:"judging from ...",ja:"…から判断すると"},
{no:1060,en:"considering ...",ja:"…を考慮すると"},
{no:1061,en:"weather permitting",ja:"天気がよければ"},
{no:1062,en:"with one's arms folded",ja:"腕を組んで"},
{no:1063,en:"had better do",ja:"～しなさい"},
{no:1064,en:"ought to do",ja:"～するべきだ"},
{no:1065,en:"need not do",ja:"～する必要がない"},
{no:1066,en:"there is no -ing",ja:"～できない"},
{no:1067,en:"feel like -ing",ja:"～したい気がする"},
{no:1068,en:"How about -ing?",ja:"～するのはどうですか"},
{no:1069,en:"look forward to -ing",ja:"～するのを楽しみに待つ"},
{no:1070,en:"be used to -ing",ja:"～するのに慣れている"},
{no:1071,en:"object to -ing",ja:"～するのに反対する"},
{no:1072,en:"when it comes to -ing",ja:"～するということになると"},
{no:1073,en:"need -ing",ja:"～される必要がある"},
{no:1074,en:"it goes without saying that ...",ja:"…は言うまでもない"},
{no:1075,en:"profit",ja:"（金銭的な）利益"},
{no:1076,en:"benefit",ja:"利益"},
{no:1077,en:"wealth",ja:"富"},
{no:1078,en:"value",ja:"価値"},
{no:1079,en:"capital",ja:"資本（金）"},
{no:1080,en:"share",ja:"分け前"},
{no:1081,en:"bet",ja:"（を）賭ける"},
{no:1082,en:"arms",ja:"武器"},
{no:1083,en:"forces",ja:"軍隊"},
{no:1084,en:"goods",ja:"商品"},
{no:1085,en:"means",ja:"手段"},
{no:1086,en:"spirits",ja:"気分"},
{no:1087,en:"height",ja:"高さ"},
{no:1088,en:"broad",ja:"広い"},
{no:1089,en:"huge",ja:"巨大な"},
{no:1090,en:"tiny",ja:"とても小さい"},
{no:1091,en:"single",ja:"たった1つの"},
{no:1092,en:"depth",ja:"深さ"},
{no:1093,en:"widespread",ja:"幅広い"},
{no:1094,en:"fare",ja:"（鉄道などの）運賃"},
{no:1095,en:"fee",ja:"（入学や入会などの）料金"},
{no:1096,en:"bill",ja:"請求書"},
{no:1097,en:"admission",ja:"入場料"},
{no:1098,en:"tax",ja:"税金"},
{no:1099,en:"vote",ja:"投票する"},
{no:1100,en:"earn",ja:"を稼ぐ"},
{no:1101,en:"employ",ja:"を雇う"},
{no:1102,en:"hire",ja:"（一時的に）を雇う"},
{no:1103,en:"export",ja:"を輸出する"},
{no:1104,en:"import",ja:"を輸入する"},
{no:1105,en:"protect",ja:"を保護する"},
{no:1106,en:"deliver",ja:"（演説・演技など）をする"},
{no:1107,en:"retail",ja:"小売り"},
{no:1108,en:"income",ja:"（給与・年金などの）収入"},
{no:1109,en:"salary",ja:"（知的労働に対する）給与"},
{no:1110,en:"wage",ja:"（肉体労働に対する）賃金"},
{no:1111,en:"commission",ja:"報酬"},
{no:1112,en:"delay",ja:"を遅らせる"},
{no:1113,en:"disturb",ja:"のじゃまをする"},
{no:1114,en:"bother",ja:"のじゃまをする"},
{no:1115,en:"ignore",ja:"を無視する"},
{no:1116,en:"trick",ja:"をだます"},
{no:1117,en:"beg",ja:"（を）請う"},
{no:1118,en:"client",ja:"（弁護士など専門職への）依頼人"},
{no:1119,en:"audience",ja:"観客"},
{no:1120,en:"spectator",ja:"（試合やイベントの）観客"},
{no:1121,en:"passenger",ja:"（乗り物の）乗客"},
{no:1122,en:"customer",ja:"（商店などの）顧客"},
{no:1123,en:"guest",ja:"（ホテルなどの）宿泊客"},
{no:1124,en:"hospitality",ja:"親切なもてなし"},
{no:1125,en:"separate",ja:"を分ける"},
{no:1126,en:"connect",ja:"をつなぐ"},
{no:1127,en:"consist",ja:"…から成る"},
{no:1128,en:"compare",ja:"を比較する"},
{no:1129,en:"reserve",ja:"を取っておく"},
{no:1130,en:"assess",ja:"（財産・収入など）を評価する"},
{no:1131,en:"work",ja:"仕事"},
{no:1132,en:"labor",ja:"（苦痛を伴う）労働"},
{no:1133,en:"job",ja:"（具体的な内容の）仕事"},
{no:1134,en:"task",ja:"（一定期間ですべき）仕事"},
{no:1135,en:"profession",ja:"（知的・専門的な）職業"},
{no:1136,en:"occupation",ja:"職業"},
{no:1137,en:"carriage",ja:"馬車"},
{no:1138,en:"load",ja:"積み荷"},
{no:1139,en:"wheel",ja:"ハンドル"},
{no:1140,en:"commute",ja:"通勤する"},
{no:1141,en:"migration",ja:"移住"},
{no:1142,en:"hard",ja:"激しく"},
{no:1143,en:"shortly",ja:"まもなく"},
{no:1144,en:"just",ja:"ちょうど"},
{no:1145,en:"justly",ja:"公正に"},
{no:1146,en:"late",ja:"遅れて"},
{no:1147,en:"lately",ja:"最近"},
{no:1148,en:"near",ja:"～の近くに"},
{no:1149,en:"nearly",ja:"ほとんど"},
{no:1150,en:"living",ja:"生きている"},
{no:1151,en:"priceless",ja:"たいへん貴重な"},
{no:1152,en:"worthless",ja:"価値のない"},
{no:1153,en:"very",ja:"まさにその…"},
{no:1154,en:"constant",ja:"一定の"},
{no:1155,en:"strict",ja:"（人が）厳しい"},
{no:1156,en:"most",ja:"もっとも"},
{no:1157,en:"mostly",ja:"たいていは"},
{no:1158,en:"pretty",ja:"かなり"},
{no:1159,en:"prettily",ja:"かわいらしく"},
{no:1160,en:"sharp",ja:"きっかりと"},
{no:1161,en:"sharply",ja:"鋭く"},
{no:1162,en:"figure",ja:"数字"},
{no:1163,en:"sum",ja:"合計"},
{no:1164,en:"quantity",ja:"量"},
{no:1165,en:"quarter",ja:"4分の1"},
{no:1166,en:"double",ja:"2倍になる"},
{no:1167,en:"transport",ja:"を輸送する"},
{no:1168,en:"transfer",ja:"転勤する"},
{no:1169,en:"wander",ja:"歩き回る"},
{no:1170,en:"shift",ja:"少し動く"},
{no:1171,en:"depart",ja:"出発する"},
{no:1172,en:"convey",ja:"（思想・意味など）を伝える"},
{no:1173,en:"descend",ja:"（を）降りる"},
{no:1174,en:"immigrate",ja:"（外国から）移住する"},
{no:1175,en:"chairperson",ja:"議長"},
{no:1176,en:"conference",ja:"会議"},
{no:1177,en:"financial",ja:"財政上の"},
{no:1178,en:"firm",ja:"会社"},
{no:1179,en:"item",ja:"（新聞）記事"},
{no:1180,en:"manager",ja:"経営者"},
{no:1181,en:"secretary",ja:"秘書"},
{no:1182,en:"signature",ja:"署名"},
{no:1183,en:"undertake",ja:"を引き受ける"},
{no:1184,en:"fulfill",ja:"（義務・約束）を果たす"},
{no:1185,en:"establish",ja:"を設立する"},
{no:1186,en:"construct",ja:"を建設する"},
{no:1187,en:"maintain",ja:"を維持する"},
{no:1188,en:"engage",ja:"…に従事している"},
{no:1189,en:"slip",ja:"紙片"},
{no:1190,en:"staff",ja:"職員"},
{no:1191,en:"suit",ja:"スーツ"},
{no:1192,en:"manual",ja:"手で行う"},
{no:1193,en:"deal",ja:"…を扱う"},
{no:1194,en:"brand",ja:"銘柄"},
{no:1195,en:"congratulate",ja:"を祝う"},
{no:1196,en:"assure",ja:"に確信させる"},
{no:1197,en:"declare",ja:"を宣言する"},
{no:1198,en:"illustrate",ja:"（実例・図により）を説明する"},
{no:1199,en:"demonstrate",ja:"を明確に示す"},
{no:1200,en:"exhibit",ja:"を展示する"},
{no:1201,en:"holy",ja:"神聖な"},
{no:1202,en:"mercy",ja:"慈悲"},
{no:1203,en:"religious",ja:"宗教の"},
{no:1204,en:"sin",ja:"（宗教・道徳上の）罪"},
{no:1205,en:"faith",ja:"信頼"},
{no:1206,en:"belief",ja:"信念"},
{no:1207,en:"glory",ja:"栄光"},
{no:1208,en:"sacred",ja:"神聖な"},
{no:1209,en:"eternal",ja:"永遠の"},
{no:1210,en:"worship",ja:"を拝む"},
{no:1211,en:"pray",ja:"（を）祈る"},
{no:1212,en:"bless",ja:"を祝福する"},
{no:1213,en:"confess",ja:"（罪など）を告白する"},
{no:1214,en:"sacrifice",ja:"を犠牲にする"},
{no:1215,en:"ritual",ja:"儀式"},
{no:1216,en:"court",ja:"法廷"},
{no:1217,en:"lawyer",ja:"弁護士"},
{no:1218,en:"proof",ja:"証拠（品）"},
{no:1219,en:"victim",ja:"（事故などの）犠牲者"},
{no:1220,en:"witness",ja:"目撃者"},
{no:1221,en:"trial",ja:"裁判"},
{no:1222,en:"fog",ja:"霧"},
{no:1223,en:"flood",ja:"洪水"},
{no:1224,en:"typical",ja:"典型的な"},
{no:1225,en:"breeze",ja:"そよ風"},
{no:1226,en:"frost",ja:"霜"},
{no:1227,en:"moist",ja:"湿った"},
{no:1228,en:"humid",ja:"湿気の多い"},
{no:1229,en:"thermometer",ja:"温度計"},
{no:1230,en:"thunder",ja:"雷"},
{no:1231,en:"contract",ja:"契約（書）"},
{no:1232,en:"innocent",ja:"無実の"},
{no:1233,en:"justice",ja:"公正"},
{no:1234,en:"legal",ja:"合法的な"},
{no:1235,en:"prison",ja:"刑務所"},
{no:1236,en:"advocate",ja:"を主張する"},
{no:1237,en:"expose",ja:"を（危険や光などに）さらす"},
{no:1238,en:"emerge",ja:"現れる"},
{no:1239,en:"reveal",ja:"を明らかにする"},
{no:1240,en:"imply",ja:"を示唆する"},
{no:1241,en:"arise",ja:"（問題などが）生まれる"},
{no:1242,en:"generate",ja:"を生み出す"},
{no:1243,en:"locate",ja:"の位置を突き止める"},
{no:1244,en:"ache",ja:"（心身の鋭い）痛み"},
{no:1245,en:"ambulance",ja:"救急車"},
{no:1246,en:"comfort",ja:"を慰める"},
{no:1247,en:"deaf",ja:"耳が聞こえない"},
{no:1248,en:"drug",ja:"薬"},
{no:1249,en:"fatigue",ja:"疲労"},
{no:1250,en:"muscle",ja:"筋肉"},
{no:1251,en:"remedy",ja:"治療"},
{no:1252,en:"symptom",ja:"症状"},
{no:1253,en:"sweat",ja:"汗"},
{no:1254,en:"bacteria",ja:"バクテリア"},
{no:1255,en:"prepare",ja:"を用意する"},
{no:1256,en:"equip",ja:"を備えつける"},
{no:1257,en:"furnish",ja:"に家具を備えつける"},
{no:1258,en:"beast",ja:"けだもの"},
{no:1259,en:"biology",ja:"生物学"},
{no:1260,en:"botany",ja:"植物学"},
{no:1261,en:"cell",ja:"細胞"},
{no:1262,en:"ecology",ja:"生態（学）"},
{no:1263,en:"feather",ja:"羽毛"},
{no:1264,en:"fur",ja:"毛皮"},
{no:1265,en:"insect",ja:"昆虫"},
{no:1266,en:"instinct",ja:"本能"},
{no:1267,en:"evolution",ja:"（生物の）進化"},
{no:1268,en:"educate",ja:"を教育する"},
{no:1269,en:"comprehend",ja:"を理解する"},
{no:1270,en:"examine",ja:"を調査する"},
{no:1271,en:"cultural",ja:"文化的な"},
{no:1272,en:"folk",ja:"民族"},
{no:1273,en:"humanity",ja:"人類"},
{no:1274,en:"inhabitant",ja:"住民"},
{no:1275,en:"primitive",ja:"原始（時代）の"},
{no:1276,en:"savage",ja:"野蛮な"},
{no:1277,en:"slave",ja:"奴隷"},
{no:1278,en:"tribe",ja:"種族"},
{no:1279,en:"ethnic",ja:"民族の"},
{no:1280,en:"migrant",ja:"出稼ぎの"},
{no:1281,en:"distinguish",ja:"を区別する"},
{no:1282,en:"review",ja:"を再検討する"},
{no:1283,en:"absorb",ja:"（知識など）を吸収する"},
{no:1284,en:"cattle",ja:"ウシ"},
{no:1285,en:"fertile",ja:"（土地が）肥えた"},
{no:1286,en:"plague",ja:"ペスト"},
{no:1287,en:"rural",ja:"いなかの"},
{no:1288,en:"weed",ja:"雑草"},
{no:1289,en:"wheat",ja:"小麦"},
{no:1290,en:"flour",ja:"小麦粉"},
{no:1291,en:"yield",ja:"産出（高）"},
{no:1292,en:"organic",ja:"有機の"},
{no:1293,en:"bind",ja:"を縛る"},
{no:1294,en:"grasp",ja:"をしっかりと握る"},
{no:1295,en:"handle",ja:"（人・もの）を取り扱う"},
{no:1296,en:"squeeze",ja:"をしぼる"},
{no:1297,en:"candidate",ja:"候補者"},
{no:1298,en:"civil",ja:"市民の"},
{no:1299,en:"congress",ja:"（米国の）連邦議会"},
{no:1300,en:"constitution",ja:"憲法"},
{no:1301,en:"kingdom",ja:"王国"},
{no:1302,en:"liberty",ja:"自由"},
{no:1303,en:"military",ja:"軍隊の"},
{no:1304,en:"stir",ja:"をかき回す"},
{no:1305,en:"tear",ja:"を裂く"},
{no:1306,en:"wipe",ja:"をふきとる"},
{no:1307,en:"stuff",ja:"を詰め込む"},
{no:1308,en:"parliament",ja:"（英国の）国会"},
{no:1309,en:"political",ja:"政治（上）の"},
{no:1310,en:"republic",ja:"共和国"},
{no:1311,en:"minister",ja:"大臣"},
{no:1312,en:"revolution",ja:"大変革"},
{no:1313,en:"treaty",ja:"条約"},
{no:1314,en:"governor",ja:"（州）知事"},
{no:1315,en:"convention",ja:"代表者会議"},
{no:1316,en:"abolish",ja:"を廃止する"},
{no:1317,en:"accuse",ja:"を告発する"},
{no:1318,en:"commit",ja:"（罪・過ちなど）を犯す"},
{no:1319,en:"inherit",ja:"を相続する"},
{no:1320,en:"atom",ja:"原子"},
{no:1321,en:"mass",ja:"大きなかたまり"},
{no:1322,en:"nuclear",ja:"核の"},
{no:1323,en:"oxygen",ja:"酸素"},
{no:1324,en:"hydrogen",ja:"水素"},
{no:1325,en:"sphere",ja:"球"},
{no:1326,en:"microscope",ja:"顕微鏡"},
{no:1327,en:"chloride",ja:"塩化物"},
{no:1328,en:"acid",ja:"酸性の"},
{no:1329,en:"compound",ja:"化合物"},
{no:1330,en:"appoint",ja:"を任命する"},
{no:1331,en:"govern",ja:"を統治する"},
{no:1332,en:"impose",ja:"～に…を課す"},
{no:1333,en:"district",ja:"（特色・機能を持った）地域"},
{no:1334,en:"geography",ja:"地理（学）"},
{no:1335,en:"globe",ja:"地球"},
{no:1336,en:"harbor",ja:"港"},
{no:1337,en:"region",ja:"地方"},
{no:1338,en:"route",ja:"道（筋）"},
{no:1339,en:"territory",ja:"領土"},
{no:1340,en:"urban",ja:"都市の"},
{no:1341,en:"range",ja:"範囲"},
{no:1342,en:"protest",ja:"抗議する"},
{no:1343,en:"oppose",ja:"に反対する"},
{no:1344,en:"interrupt",ja:"に口をはさむ"},
{no:1345,en:"interfere",ja:"…に支障をきたす"},
{no:1346,en:"diverse",ja:"（はっきり）異なった"},
{no:1347,en:"density",ja:"密集"},
{no:1348,en:"empire",ja:"帝国"},
{no:1349,en:"journal",ja:"（専門の）雑誌"},
{no:1350,en:"racial",ja:"人種の"},
{no:1351,en:"basis",ja:"基礎"},
{no:1352,en:"bump",ja:"衝突（音）"},
{no:1353,en:"council",ja:"議会"},
{no:1354,en:"outcome",ja:"結果"},
{no:1355,en:"platform",ja:"壇"},
{no:1356,en:"priority",ja:"優先（権）"},
{no:1357,en:"prize",ja:"賞"},
{no:1358,en:"storage",ja:"保管（場所）"},
{no:1359,en:"uncertainty",ja:"不確実（性）"},
{no:1360,en:"figure out ...",ja:"…を理解する"},
{no:1361,en:"pass on ～ to ...",ja:"～を…に伝える"},
{no:1362,en:"pay off (...)",ja:"（計画などが）うまくいく"},
{no:1363,en:"work out (...)",ja:"（計画など）を考え出す"},
{no:1364,en:"cut in",ja:"じゃまをする"},
{no:1365,en:"pull up (...)",ja:"車を止める"},
{no:1366,en:"pull one's leg",ja:"～をからかう"},
{no:1367,en:"hit on ...",ja:"…を思いつく"},
{no:1368,en:"fall out",ja:"口論する"},
{no:1369,en:"live up to ...",ja:"（評判・期待など）に応える"},
{no:1370,en:"answer for ...",ja:"…の責任を負う"},
{no:1371,en:"change shirts",ja:"シャツを着替える"},
{no:1372,en:"change trains",ja:"列車を乗り換える"},
{no:1373,en:"shake hands",ja:"握手をする"},
{no:1374,en:"behind the times",ja:"時代遅れの"},
{no:1375,en:"as (of) yet",ja:"まだ～（ない）"},
{no:1376,en:"in advance",ja:"前もって"},
{no:1377,en:"in no time",ja:"すぐに"},
{no:1378,en:"before long",ja:"まもなく"},
{no:1379,en:"for good",ja:"永久に"},
{no:1380,en:"would (often) do",ja:"（よく）～したものだった"},
{no:1381,en:"would like to do",ja:"～したいと思う"},
{no:1382,en:"cannot be too ...",ja:"いくら…してもしすぎではない"},
{no:1383,en:"cannot ... enough",ja:"いくら…してもし足りない"},
{no:1384,en:"may well do",ja:"～するのももっともだ"},
{no:1385,en:"may as well do",ja:"～したほうがよい"},
{no:1386,en:"may as well ... as ～",ja:"～するくらいなら…するほうがましだ"},
{no:1387,en:"How dare ... (?)",ja:"よくもずうずうしく…"},
{no:1388,en:"be in charge of ...",ja:"…の担当である"},
{no:1389,en:"be up to ...",ja:"…の責任である"},
{no:1390,en:"be yet to do",ja:"まだ～していない"},
{no:1391,en:"be well off",ja:"裕福である"},
{no:1392,en:"be through with ...",ja:"…を終える"},
{no:1393,en:"be under way",ja:"進行中である"},
{no:1394,en:"be at home in ...",ja:"…に慣れている"},
{no:1395,en:"be on good terms with ...",ja:"…と仲がよい"},
{no:1396,en:"be as good as one's word",ja:"約束を果たす"},
{no:1397,en:"be beside the point",ja:"的外れである"},
{no:1398,en:"not so much A as B",ja:"AというよりはむしろB"},
{no:1399,en:"not so much as do",ja:"～さえしない"},
{no:1400,en:"as ... as any ～",ja:"どの～にも劣らず…"},
{no:1401,en:"as many as ...",ja:"…も（の）"},
{no:1402,en:"provided (that) ...",ja:"もし…ならば"},
{no:1403,en:"on condition that ...",ja:"…という条件で"},
{no:1404,en:"even if ...",ja:"たとえ…だとしても"},
{no:1405,en:"although ...",ja:"…だけれども"},
{no:1406,en:"unless ...",ja:"…しない限り"},
{no:1407,en:"形容詞＋as ...",ja:"～ではあるが"},
{no:1408,en:"whereas ...",ja:"ところが（それに対して）"},
{no:1409,en:"whether ... or not",ja:"…しようがしまいが"},
{no:1410,en:"no more than ...",ja:"…しか～ない"},
{no:1411,en:"not more than ...",ja:"せいぜい…しか～ない"},
{no:1412,en:"no less than ...",ja:"…も"},
{no:1413,en:"not less than ...",ja:"少なくとも…"},
{no:1414,en:"A is no more B than C is D",ja:"CがDでないのと同様にAはBでない"},
{no:1415,en:"A is no less B than C is D",ja:"CがDであるのと同様にAはBである"},
{no:1416,en:"by way of ...",ja:"…経由で"},
{no:1417,en:"without fail",ja:"必ず"},
{no:1418,en:"apart from ...",ja:"…を除いては"},
{no:1419,en:"to one's taste",ja:"～の好みに合った"},
{no:1420,en:"on second thought(s)",ja:"考え直して"},
{no:1421,en:"at large",ja:"つかまっていない"},
{no:1422,en:"behind one's back",ja:"～のいないところで"},
{no:1423,en:"the＋比較級 ..., the＋比較級 ～",ja:"…すればするほど～"},
{no:1424,en:"all the＋比較級",ja:"ますます～"},
{no:1425,en:"none the＋比較級",ja:"～というわけではない"},
{no:1426,en:"know better than to do",ja:"～するほど愚かではない"},
{no:1427,en:"be interested in ...",ja:"…に興味がある"},
{no:1428,en:"be known to ...",ja:"…に知られている"},
{no:1429,en:"be covered with ...",ja:"…で覆われている"},
{no:1430,en:"be caught in ...",ja:"（雨など）にあう"},
{no:1431,en:"be satisfied with ...",ja:"…に満足している"},
{no:1432,en:"be injured in ...",ja:"（事故など）でけがをする"},
{no:1433,en:"be killed in ...",ja:"（事故・戦争など）で死ぬ"},
{no:1434,en:"what one is (today)",ja:"現在の～"},
{no:1435,en:"what one was",ja:"以前の～"},
{no:1436,en:"A is to B what C is to D",ja:"AのBに対する関係はCのDに対する関係に等しい"},
{no:1437,en:"what is called ...",ja:"いわゆる…"},
{no:1438,en:"what is worse",ja:"さらに悪いことに"},
{no:1439,en:"what one has",ja:"～の財産"},
{no:1440,en:"what with ... and ～",ja:"…やら～やらで"},
{no:1441,en:"I wish＋仮定法",ja:"～ならいいと思う"},
{no:1442,en:"if S were to do",ja:"もしSが～するようなことがあれば"},
{no:1443,en:"if S should do",ja:"万一Sが～すれば"},
{no:1444,en:"but for ...",ja:"…がなければ"},
{no:1445,en:"with ...",ja:"…があれば"},
{no:1446,en:"if it were not for ...",ja:"もし…がなければ"},
{no:1447,en:"if it had not been for ...",ja:"もし…がなかったら"},
{no:1448,en:"it's time＋仮定法過去",ja:"もう～してもよいころだ"},
{no:1449,en:"if only＋仮定法",ja:"（せめて）～ならいいと思う"},
{no:1450,en:"as if＋仮定法",ja:"まるで～であるかのように"},
{no:1451,en:"apply to ...",ja:"…に適用される"},
{no:1452,en:"apply for ...",ja:"（職など）に応募する"},
{no:1453,en:"ask〈人〉for ...",ja:"〈人〉に…を求める"},
{no:1454,en:"care for ...",ja:"…を望む"},
{no:1455,en:"attend to ...",ja:"…に注意を払う"},
{no:1456,en:"cope with ...",ja:"…にうまく対処する"},
{no:1457,en:"attribute ... to～",ja:"…を～に起因すると考える"},
{no:1458,en:"think better of ...",ja:"…を考え直してやめる"},
{no:1459,en:"refrain from -ing",ja:"～するのを差し控える"},
{no:1460,en:"prohibit〈人〉from -ing",ja:"〈人〉が～するのを禁止する"},
{no:1461,en:"see to it that ...",ja:"…するよう気をつける"},
{no:1462,en:"persuade〈人〉into -ing",ja:"〈人〉を説得して～させる"},
{no:1463,en:"lay off ...",ja:"…を解雇する"},
{no:1464,en:"overtake",ja:"を追い越す"},
{no:1465,en:"pursue",ja:"を追求する"},
{no:1466,en:"trace",ja:"を捜し出す"},
{no:1467,en:"track",ja:"を追跡する"},
{no:1468,en:"bilingual",ja:"2言語使用の"},
{no:1469,en:"interpret",ja:"（を）通訳する"},
{no:1470,en:"fluent",ja:"流暢な"},
{no:1471,en:"acquire",ja:"（努力して）を獲得する"},
{no:1472,en:"describe",ja:"を詳しく説明する"},
{no:1473,en:"transmit",ja:"を送信する"},
{no:1474,en:"gesture",ja:"身ぶり"},
{no:1475,en:"verbal",ja:"口頭の"},
{no:1476,en:"weigh",ja:"の重さを量る"},
{no:1477,en:"calculate",ja:"（を）計算する"},
{no:1478,en:"multiply",ja:"（数）を掛ける"},
{no:1479,en:"lower",ja:"を下げる"},
{no:1480,en:"ratio",ja:"比率"},
{no:1481,en:"dialect",ja:"方言"},
{no:1482,en:"accent",ja:"なまり"},
{no:1483,en:"tongue",ja:"言語"},
{no:1484,en:"command",ja:"（言語などを）自由にあやつる能力"},
{no:1485,en:"character",ja:"（文）字"},
{no:1486,en:"letter",ja:"（文）字"},
{no:1487,en:"retain",ja:"を保持する"},
{no:1488,en:"assume",ja:"…と思い込む"},
{no:1489,en:"acknowledge",ja:"を認める"},
{no:1490,en:"contrast",ja:"を対比する"},
{no:1491,en:"derive",ja:"を得る"},
{no:1492,en:"recall",ja:"を思い出す"},
{no:1493,en:"detect",ja:"を発見する"},
{no:1494,en:"classify",ja:"を分類する"},
{no:1495,en:"vocabulary",ja:"語い力"},
{no:1496,en:"usage",ja:"語法"},
{no:1497,en:"translate",ja:"（を）翻訳する"},
{no:1498,en:"code",ja:"法"},
{no:1499,en:"represent",ja:"を表現する"},
{no:1500,en:"accustom",ja:"に慣らす"},
{no:1501,en:"adapt",ja:"…を～に適合させる"},
{no:1502,en:"attach",ja:"をくっつける"},
{no:1503,en:"differ",ja:"異なる"},
{no:1504,en:"vary",ja:"異なる"},
{no:1505,en:"linguistic",ja:"言語の"},
{no:1506,en:"context",ja:"文脈"},
{no:1507,en:"bias",ja:"先入観"},
{no:1508,en:"communication",ja:"伝達"},
{no:1509,en:"define",ja:"を定義する"},
{no:1510,en:"express",ja:"（意見・感情など）を表現する"},
{no:1511,en:"native",ja:"自国の"},
{no:1512,en:"compete",ja:"競争する"},
{no:1513,en:"confront",ja:"に立ちはだかる"},
{no:1514,en:"defeat",ja:"（敵・相手）を破る"},
{no:1515,en:"defend",ja:"を防御する"},
{no:1516,en:"intellect",ja:"知性"},
{no:1517,en:"intelligent",ja:"頭のよい"},
{no:1518,en:"skill",ja:"技術"},
{no:1519,en:"qualify",ja:"資格がある"},
{no:1520,en:"ability",ja:"能力"},
{no:1521,en:"potential",ja:"可能性"},
{no:1522,en:"award",ja:"賞"},
{no:1523,en:"honor",ja:"名誉"},
{no:1524,en:"extend",ja:"伸びる"},
{no:1525,en:"strain",ja:"（無理をして）を痛める"},
{no:1526,en:"stretch",ja:"を伸ばす"},
{no:1527,en:"proceed",ja:"…を続ける"},
{no:1528,en:"promote",ja:"を促進する"},
{no:1529,en:"prevail",ja:"…に広まる"},
{no:1530,en:"discipline",ja:"訓練"},
{no:1531,en:"concentrate",ja:"（…を）～に集中する"},
{no:1532,en:"stimulate",ja:"を刺激する"},
{no:1533,en:"evaluate",ja:"（価値・能力など）を評価する"},
{no:1534,en:"neglect",ja:"の管理をおろそかにする"},
{no:1535,en:"voluntary",ja:"自発的な"},
{no:1536,en:"insult",ja:"を侮辱する"},
{no:1537,en:"despise",ja:"を軽蔑する"},
{no:1538,en:"dispute",ja:"に反論する"},
{no:1539,en:"dominate",ja:"（で）優勢である"},
{no:1540,en:"offend",ja:"の感情を害する"},
{no:1541,en:"bully",ja:"をいじめる"},
{no:1542,en:"betray",ja:"を裏切る"},
{no:1543,en:"deceive",ja:"をだます"},
{no:1544,en:"frustrate",ja:"（計画・希望など）を挫折させる"},
{no:1545,en:"research",ja:"（学術）調査"},
{no:1546,en:"theory",ja:"理論"},
{no:1547,en:"perspective",ja:"考え方"},
{no:1548,en:"practical",ja:"実践的な"},
{no:1549,en:"academic",ja:"学問的な"},
{no:1550,en:"astonish",ja:"を驚かせる"},
{no:1551,en:"embarrass",ja:"に恥ずかしい思いをさせる"},
{no:1552,en:"fascinate",ja:"を魅了する"},
{no:1553,en:"frighten",ja:"を怖がらせる"},
{no:1554,en:"scare",ja:"を怖がらせる"},
{no:1555,en:"impress",ja:"に感銘を与える"},
{no:1556,en:"boast",ja:"（を）自慢する"},
{no:1557,en:"resolve",ja:"を解決する"},
{no:1558,en:"accomplish",ja:"を成し遂げる"},
{no:1559,en:"achievement",ja:"業績"},
{no:1560,en:"emphasize",ja:"を強調する"},
{no:1561,en:"institution",ja:"施設"},
{no:1562,en:"statistics",ja:"統計"},
{no:1563,en:"capture",ja:"を捕まえる"},
{no:1564,en:"conquer",ja:"を征服する"},
{no:1565,en:"invade",ja:"を侵略する"},
{no:1566,en:"occupy",ja:"を占める"},
{no:1567,en:"release",ja:"を解放する"},
{no:1568,en:"colony",ja:"植民地"},
{no:1569,en:"faculty",ja:"（特殊な）能力"},
{no:1570,en:"genius",ja:"天才性"},
{no:1571,en:"intellectual",ja:"知的な"},
{no:1572,en:"lecture",ja:"講義"},
{no:1573,en:"scholar",ja:"学者"},
{no:1574,en:"laboratory",ja:"研究所（室）"},
{no:1575,en:"specialize",ja:"…を専門にする"},
{no:1576,en:"resist",ja:"に抵抗する"},
{no:1577,en:"persist",ja:"…に固執する"},
{no:1578,en:"endure",ja:"を耐える"},
{no:1579,en:"invest",ja:"（金・資本など）を投資する"},
{no:1580,en:"maternal",ja:"母親の"},
{no:1581,en:"spoil",ja:"を台なしにする"},
{no:1582,en:"authority",ja:"権威（者）"},
{no:1583,en:"unique",ja:"独特な"},
{no:1584,en:"capacity",ja:"能力"},
{no:1585,en:"reject",ja:"（計画・提案など）を拒絶する"},
{no:1586,en:"decline",ja:"（申し出・誘いなど）を断る"},
{no:1587,en:"dismiss",ja:"（考えなど）を退ける"},
{no:1588,en:"garbage",ja:"ごみ"},
{no:1589,en:"destruction",ja:"破壊"},
{no:1590,en:"exploit",ja:"を開発する"},
{no:1591,en:"chemical",ja:"化学物質"},
{no:1592,en:"damage",ja:"損害"},
{no:1593,en:"energy",ja:"エネルギー"},
{no:1594,en:"fossil",ja:"化石"},
{no:1595,en:"rescue",ja:"を救助する"},
{no:1596,en:"assist",ja:"（を）補助する"},
{no:1597,en:"ensure",ja:"を保証する"},
{no:1598,en:"consult",ja:"（専門家）に意見を求める"},
{no:1599,en:"contribute",ja:"（に）貢献する"},
{no:1600,en:"devote",ja:"（時間・努力など）を～に捧げる"},
{no:1601,en:"issue",ja:"（刊行物など）を発行する"},
{no:1602,en:"distribute",ja:"を配る"},
{no:1603,en:"grant",ja:"を授与する"},
{no:1604,en:"expand",ja:"拡大する"},
{no:1605,en:"limit",ja:"を制限する"},
{no:1606,en:"poison",ja:"毒（素）"},
{no:1607,en:"emission",ja:"排出"},
{no:1608,en:"assemble",ja:"集まる"},
{no:1609,en:"combine",ja:"を結合させる"},
{no:1610,en:"encounter",ja:"（思いがけず）と出会う"},
{no:1611,en:"accompany",ja:"に同行する"},
{no:1612,en:"compose",ja:"を構成する"},
{no:1613,en:"atmosphere",ja:"大気"},
{no:1614,en:"drought",ja:"干ばつ"},
{no:1615,en:"cultivate",ja:"を耕す"},
{no:1616,en:"species",ja:"（生物の）種"},
{no:1617,en:"starve",ja:"飢え死にする"},
{no:1618,en:"preserve",ja:"を保存する"},
{no:1619,en:"ecosystem",ja:"生態系"},
{no:1620,en:"gaze",ja:"…を見つめる"},
{no:1621,en:"glance",ja:"ちらりと見る"},
{no:1622,en:"glimpse",ja:"をちらりと見る"},
{no:1623,en:"environment",ja:"（自然の）環境"},
{no:1624,en:"conservation",ja:"保護"},
{no:1625,en:"electricity",ja:"電気"},
{no:1626,en:"pollution",ja:"汚染"},
{no:1627,en:"vehicle",ja:"乗り物"},
{no:1628,en:"chemistry",ja:"化学"},
{no:1629,en:"disaster",ja:"災害"},
{no:1630,en:"crisis",ja:"危機"},
{no:1631,en:"alternative",ja:"代わりの"},
{no:1632,en:"cease",ja:"～するのをやめる"},
{no:1633,en:"conclude",ja:"と結論づける"},
{no:1634,en:"vanish",ja:"（突然）姿を消す"},
{no:1635,en:"bury",ja:"を埋葬する"},
{no:1636,en:"collapse",ja:"壊れる"},
{no:1637,en:"abandon",ja:"を捨てる"},
{no:1638,en:"fade",ja:"色あせる"},
{no:1639,en:"advertise",ja:"（を）広告する"},
{no:1640,en:"commercial",ja:"広告（放送）"},
{no:1641,en:"product",ja:"製品"},
{no:1642,en:"purchase",ja:"を購入する"},
{no:1643,en:"depression",ja:"不況"},
{no:1644,en:"rate",ja:"率"},
{no:1645,en:"conceal",ja:"を隠す"},
{no:1646,en:"exclude",ja:"を除外する"},
{no:1647,en:"omit",ja:"を省く"},
{no:1648,en:"overlook",ja:"を見落とす"},
{no:1649,en:"budget",ja:"予算"},
{no:1650,en:"proportion",ja:"割合"},
{no:1651,en:"commerce",ja:"商業"},
{no:1652,en:"credit",ja:"信用販売"},
{no:1653,en:"commodity",ja:"商品"},
{no:1654,en:"disadvantage",ja:"不利"},
{no:1655,en:"debt",ja:"借金"},
{no:1656,en:"domestic",ja:"国内の"},
{no:1657,en:"asset",ja:"資産"},
{no:1658,en:"compromise",ja:"妥協する"},
{no:1659,en:"correspond",ja:"一致する"},
{no:1660,en:"relate",ja:"関係がある"},
{no:1661,en:"enterprise",ja:"事業"},
{no:1662,en:"expense",ja:"費用"},
{no:1663,en:"fund",ja:"基金"},
{no:1664,en:"growth",ja:"成長"},
{no:1665,en:"stock",ja:"在庫（品）"},
{no:1666,en:"childhood",ja:"幼年時代"},
{no:1667,en:"infant",ja:"乳児"},
{no:1668,en:"prime",ja:"絶頂期"},
{no:1669,en:"popularity",ja:"人気"},
{no:1670,en:"philosophy",ja:"哲学"},
{no:1671,en:"thought",ja:"考え"},
{no:1672,en:"aim",ja:"目的"},
{no:1673,en:"destination",ja:"目的地"},
{no:1674,en:"motivate",ja:"に動機を与える"},
{no:1675,en:"undergo",ja:"を経験する"},
{no:1676,en:"welfare",ja:"幸福"},
{no:1677,en:"pension",ja:"年金"},
{no:1678,en:"insurance",ja:"保険"},
{no:1679,en:"isolation",ja:"孤立"},
{no:1680,en:"shortage",ja:"不足"},
{no:1681,en:"ambitious",ja:"野心のある"},
{no:1682,en:"significant",ja:"意義深い"},
{no:1683,en:"splendid",ja:"すばらしい"},
{no:1684,en:"vivid",ja:"鮮明な"},
{no:1685,en:"vital",ja:"不可欠な"},
{no:1686,en:"ancestor",ja:"先祖"},
{no:1687,en:"heritage",ja:"遺産"},
{no:1688,en:"poverty",ja:"貧困"},
{no:1689,en:"abuse",ja:"虐待"},
{no:1690,en:"improve",ja:"を向上させる"},
{no:1691,en:"circumstance",ja:"（周囲の）状況"},
{no:1692,en:"funeral",ja:"葬式"},
{no:1693,en:"grave",ja:"墓"},
{no:1694,en:"cancer",ja:"ガン"},
{no:1695,en:"suicide",ja:"自殺"},
{no:1696,en:"rumor",ja:"うわさ"},
{no:1697,en:"reputation",ja:"評判"},
{no:1698,en:"fame",ja:"名声"},
{no:1699,en:"emergency",ja:"緊急時"},
{no:1700,en:"relief",ja:"安堵"},
{no:1701,en:"formal",ja:"正式の"},
{no:1702,en:"involve",ja:"を巻き込む"},
{no:1703,en:"barrier",ja:"障壁"},
{no:1704,en:"violation",ja:"違反（行為）"},
{no:1705,en:"endangered",ja:"絶滅の危機に瀕した"},
{no:1706,en:"extinction",ja:"絶滅"},
{no:1707,en:"discrimination",ja:"差別"},
{no:1708,en:"disorder",ja:"不調"},
{no:1709,en:"virus",ja:"ウイルス"},
{no:1710,en:"ban",ja:"を禁止する"},
{no:1711,en:"restrict",ja:"を制限する"},
{no:1712,en:"envious",ja:"うらやんで"},
{no:1713,en:"scorn",ja:"軽蔑"},
{no:1714,en:"remote",ja:"人里離れた"},
{no:1715,en:"apart",ja:"離れて"},
{no:1716,en:"aside",ja:"わきへ"},
{no:1717,en:"forth",ja:"外へ"},
{no:1718,en:"divorce",ja:"離婚"},
{no:1719,en:"chief",ja:"もっとも重要な"},
{no:1720,en:"fair",ja:"適正な"},
{no:1721,en:"reliable",ja:"信頼できる"},
{no:1722,en:"secure",ja:"安定した"},
{no:1723,en:"consistent",ja:"首尾一貫した"},
{no:1724,en:"sophisticated",ja:"精巧な"},
{no:1725,en:"willing",ja:"いとわない"},
{no:1726,en:"attain",ja:"（に）到達する"},
{no:1727,en:"incentive",ja:"刺激"},
{no:1728,en:"historic",ja:"歴史のある"},
{no:1729,en:"historical",ja:"歴史に関する"},
{no:1730,en:"historian",ja:"歴史家"},
{no:1731,en:"anthropologist",ja:"人類学者"},
{no:1732,en:"root",ja:"根"},
{no:1733,en:"renew",ja:"（を）更新する"},
{no:1734,en:"alter",ja:"を変える"},
{no:1735,en:"transform",ja:"を変形させる"},
{no:1736,en:"inspire",ja:"を奮起させる"},
{no:1737,en:"modify",ja:"を修正する"},
{no:1738,en:"tie",ja:"を結びつける"},
{no:1739,en:"convert",ja:"を変える"},
{no:1740,en:"enhance",ja:"を高める"},
{no:1741,en:"reform",ja:"改革"},
{no:1742,en:"draft",ja:"草案"},
{no:1743,en:"legitimate",ja:"合法の"},
{no:1744,en:"valid",ja:"有効な"},
{no:1745,en:"drastic",ja:"抜本的な"},
{no:1746,en:"radical",ja:"根本的な"},
{no:1747,en:"submit",ja:"を提出する"},
{no:1748,en:"donate",ja:"（を）寄付する"},
{no:1749,en:"register",ja:"（を）登録する"},
{no:1750,en:"sustainable",ja:"環境を破壊しない"},
{no:1751,en:"quality",ja:"質"},
{no:1752,en:"inclusive",ja:"（すべて）含んだ"},
{no:1753,en:"equality",ja:"平等"},
{no:1754,en:"empower",ja:"に権限を与える"},
{no:1755,en:"gender",ja:"性（別）"},
{no:1756,en:"diversity",ja:"多様性"},
{no:1757,en:"affordable",ja:"（値段が）手ごろな"},
{no:1758,en:"productive",ja:"生産的な"},
{no:1759,en:"employment",ja:"雇用"},
{no:1760,en:"foster",ja:"を育てる"},
{no:1761,en:"settlement",ja:"解決"},
{no:1762,en:"consumption",ja:"消費（量）"},
{no:1763,en:"urgent",ja:"緊急の"},
{no:1764,en:"combat",ja:"戦闘"},
{no:1765,en:"climate",ja:"（年間を通じての）気候"},
{no:1766,en:"conserve",ja:"を保存する"},
{no:1767,en:"reverse",ja:"を覆す"},
{no:1768,en:"effective",ja:"効果的な"},
{no:1769,en:"accountable",ja:"責任がある"},
{no:1770,en:"implementation",ja:"履行"},
{no:1771,en:"boost",ja:"を後押しする"},
{no:1772,en:"embrace",ja:"を抱きしめる"},
{no:1773,en:"infer",ja:"を推論する"},
{no:1774,en:"mislead",ja:"を迷わせる"},
{no:1775,en:"overwhelm",ja:"を圧倒する"},
{no:1776,en:"retrieve",ja:"を取り戻す"},
{no:1777,en:"utilize",ja:"を使う"},
{no:1778,en:"external",ja:"外の"},
{no:1779,en:"neutral",ja:"中立の"},
{no:1780,en:"relevant",ja:"（密接な）関連がある"},
{no:1781,en:"accordingly",ja:"したがって"},
{no:1782,en:"definitely",ja:"確かに"},
{no:1783,en:"deliberately",ja:"慎重に"},
{no:1784,en:"virtually",ja:"事実上"},
{no:1785,en:"good",ja:"よい"},
{no:1786,en:"right",ja:"正しい"},
{no:1787,en:"use",ja:"使用"},
{no:1788,en:"mean",ja:"を意味する"},
{no:1789,en:"order",ja:"命令"},
{no:1790,en:"case",ja:"（個々の）場合"},
{no:1791,en:"way",ja:"道"},
{no:1792,en:"sound",ja:"音"},
{no:1793,en:"sense",ja:"感覚"},
{no:1794,en:"matter",ja:"（検討・対処を要する）問題"},
{no:1795,en:"respect",ja:"を尊敬する"},
{no:1796,en:"still",ja:"静かな"},
{no:1797,en:"due",ja:"到着する予定で"},
{no:1798,en:"account",ja:"勘定（書）"},
{no:1799,en:"present",ja:"を示す"},
{no:1800,en:"bear",ja:"（責任・費用など）を負う"},
{no:1801,en:"bound",ja:"縛られた"},
{no:1802,en:"term",ja:"期限"},
{no:1803,en:"fast",ja:"堅く"},
{no:1804,en:"wear",ja:"を着ている"},
{no:1805,en:"appreciate",ja:"を正しく理解する"},
{no:1806,en:"immediate",ja:"迅速な"},
{no:1807,en:"sudden",ja:"突然の"},
{no:1808,en:"temporary",ja:"一時的な"},
{no:1809,en:"burst",ja:"破裂する"},
{no:1810,en:"artificial",ja:"人工の"},
{no:1811,en:"mammal",ja:"ほ乳動物"},
{no:1812,en:"brain",ja:"脳"},
{no:1813,en:"lung",ja:"肺"},
{no:1814,en:"organ",ja:"臓器"},
{no:1815,en:"transplant",ja:"移植"},
{no:1816,en:"technology",ja:"科学技術"},
{no:1817,en:"equipment",ja:"設備"},
{no:1818,en:"innovation",ja:"（技術）革新"},
{no:1819,en:"operation",ja:"手術"},
{no:1820,en:"breakthrough",ja:"大発見"},
{no:1821,en:"contemporary",ja:"現代の"},
{no:1822,en:"nowadays",ja:"今日では"},
{no:1823,en:"recent",ja:"最近の"},
{no:1824,en:"annual",ja:"毎年の"},
{no:1825,en:"previous",ja:"先の"},
{no:1826,en:"decade",ja:"10年（間）"},
{no:1827,en:"era",ja:"（ある特定の）時代"},
{no:1828,en:"principle",ja:"原理"},
{no:1829,en:"phenomenon",ja:"現象"},
{no:1830,en:"material",ja:"物質"},
{no:1831,en:"substance",ja:"物質"},
{no:1832,en:"solid",ja:"固体"},
{no:1833,en:"liquid",ja:"液体"},
{no:1834,en:"accurate",ja:"正確な"},
{no:1835,en:"bold",ja:"大胆な"},
{no:1836,en:"modest",ja:"控えめな"},
{no:1837,en:"positive",ja:"積極的な"},
{no:1838,en:"passive",ja:"受け身の"},
{no:1839,en:"diligent",ja:"勤勉な"},
{no:1840,en:"earnest",ja:"真剣な"},
{no:1841,en:"sincere",ja:"誠実な"},
{no:1842,en:"effect",ja:"影響"},
{no:1843,en:"appearance",ja:"出現"},
{no:1844,en:"exception",ja:"例外"},
{no:1845,en:"condition",ja:"状況"},
{no:1846,en:"process",ja:"過程"},
{no:1847,en:"attribute",ja:"…を～に起因すると考える"},
{no:1848,en:"fundamental",ja:"基本的な"},
{no:1849,en:"primary",ja:"第1の"},
{no:1850,en:"foundation",ja:"土台"},
{no:1851,en:"background",ja:"（人の）生い立ち"},
{no:1852,en:"originate",ja:"起こる"},
{no:1853,en:"perceive",ja:"を知覚する"},
{no:1854,en:"experience",ja:"経験"},
{no:1855,en:"experiment",ja:"実験"},
{no:1856,en:"evidence",ja:"証拠"},
{no:1857,en:"analysis",ja:"分析"},
{no:1858,en:"hypothesis",ja:"仮説"},
{no:1859,en:"logic",ja:"論理"},
{no:1860,en:"investigate",ja:"（を）調査する"},
{no:1861,en:"appetite",ja:"食欲"},
{no:1862,en:"diet",ja:"（減量などのための）規定食"},
{no:1863,en:"hunger",ja:"飢え"},
{no:1864,en:"ripe",ja:"熟した"},
{no:1865,en:"thirst",ja:"のどの渇き"},
{no:1866,en:"apply",ja:"を応用する"},
{no:1867,en:"application",ja:"応用"},
{no:1868,en:"invent",ja:"を発明する"},
{no:1869,en:"develop",ja:"を発達させる"},
{no:1870,en:"advance",ja:"進歩"},
{no:1871,en:"dawn",ja:"夜明け"},
{no:1872,en:"landscape",ja:"景色"},
{no:1873,en:"steep",ja:"（坂などが）険しい"},
{no:1874,en:"stream",ja:"小川"},
{no:1875,en:"blow",ja:"（風が）吹き飛ばす"},
{no:1876,en:"gravity",ja:"重力"},
{no:1877,en:"reflect",ja:"を映し出す"},
{no:1878,en:"satellite",ja:"（天体の）衛星"},
{no:1879,en:"explore",ja:"を探検する"},
{no:1880,en:"orbit",ja:"（衛星などの）軌道"},
{no:1881,en:"instrument",ja:"（精密作業用の）器具"},
{no:1882,en:"universe",ja:"宇宙"},
{no:1883,en:"planet",ja:"惑星"},
{no:1884,en:"object",ja:"物体"},
{no:1885,en:"abundant",ja:"豊富な"},
{no:1886,en:"luxury",ja:"ぜいたく（品）"},
{no:1887,en:"plenty",ja:"豊富さ"},
{no:1888,en:"privilege",ja:"特権"},
{no:1889,en:"prosperity",ja:"繁栄"},
{no:1890,en:"gene",ja:"遺伝子"},
{no:1891,en:"breed",ja:"を繁殖させる"},
{no:1892,en:"device",ja:"装置"},
{no:1893,en:"medicine",ja:"医学"},
{no:1894,en:"observe",ja:"を観察する"},
{no:1895,en:"patient",ja:"患者"},
{no:1896,en:"exhaustion",ja:"極度の疲労"},
{no:1897,en:"equivalent",ja:"同等の"},
{no:1898,en:"identical",ja:"まったく同一の"},
{no:1899,en:"complicated",ja:"複雑な"},
{no:1900,en:"elaborate",ja:"手の込んだ"},
{no:1901,en:"accord",ja:"を与える"},
{no:1902,en:"counterpart",ja:"対応するもの"},
{no:1903,en:"component",ja:"構成要素"},
{no:1904,en:"layer",ja:"層"},
{no:1905,en:"molecule",ja:"分子"},
{no:1906,en:"particle",ja:"（微）粒子"},
{no:1907,en:"motion",ja:"運動"},
{no:1908,en:"intense",ja:"激しい"},
{no:1909,en:"confirm",ja:"を裏づける"},
{no:1910,en:"predict",ja:"を予測する"},
{no:1911,en:"article",ja:"記事"},
{no:1912,en:"biography",ja:"伝記"},
{no:1913,en:"comment",ja:"論評"},
{no:1914,en:"fiction",ja:"フィクション"},
{no:1915,en:"legend",ja:"伝説"},
{no:1916,en:"manuscript",ja:"原稿"},
{no:1917,en:"moral",ja:"道徳"},
{no:1918,en:"strength",ja:"力"},
{no:1919,en:"active",ja:"活動的な"},
{no:1920,en:"decent",ja:"きちんとした"},
{no:1921,en:"noble",ja:"気高い"},
{no:1922,en:"dignity",ja:"威厳"},
{no:1923,en:"wisdom",ja:"英知"},
{no:1924,en:"virtue",ja:"徳"},
{no:1925,en:"phrase",ja:"言い回し"},
{no:1926,en:"proverb",ja:"諺"},
{no:1927,en:"quote",ja:"（を）引用する"},
{no:1928,en:"remark",ja:"発言"},
{no:1929,en:"tale",ja:"物語"},
{no:1930,en:"theme",ja:"主題"},
{no:1931,en:"volume",ja:"巻"},
{no:1932,en:"pastime",ja:"気晴らし"},
{no:1933,en:"recreation",ja:"娯楽"},
{no:1934,en:"comedy",ja:"喜劇"},
{no:1935,en:"stage",ja:"舞台"},
{no:1936,en:"delight",ja:"大喜び"},
{no:1937,en:"mischief",ja:"いたずら"},
{no:1938,en:"despair",ja:"絶望"},
{no:1939,en:"grief",ja:"深い悲しみ"},
{no:1940,en:"misery",ja:"みじめさ"},
{no:1941,en:"shame",ja:"恥ずかしさ"},
{no:1942,en:"sorrow",ja:"悲しみ"},
{no:1943,en:"tragedy",ja:"悲劇"},
{no:1944,en:"sympathy",ja:"同情"},
{no:1945,en:"characteristic",ja:"独特な"},
{no:1946,en:"enthusiasm",ja:"熱狂"},
{no:1947,en:"generous",ja:"気前がよい"},
{no:1948,en:"keen",ja:"鋭い"},
{no:1949,en:"mature",ja:"成熟した"},
{no:1950,en:"nerve",ja:"度胸"},
{no:1951,en:"eager",ja:"熱望して"},
{no:1952,en:"reluctant",ja:"気の進まない"},
{no:1953,en:"abstract",ja:"抽象的な"},
{no:1954,en:"illusion",ja:"幻想"},
{no:1955,en:"obscure",ja:"（人が）無名の"},
{no:1956,en:"subtle",ja:"微妙な"},
{no:1957,en:"vague",ja:"あいまいな"},
{no:1958,en:"ambiguous",ja:"あいまいな"},
{no:1959,en:"pattern",ja:"模様"},
{no:1960,en:"architecture",ja:"建築（様式）"},
{no:1961,en:"facility",ja:"施設"},
{no:1962,en:"property",ja:"財産"},
{no:1963,en:"shelter",ja:"避難"},
{no:1964,en:"structure",ja:"構造"},
{no:1965,en:"vacant",ja:"空いている"},
{no:1966,en:"tidy",ja:"きちんと片づいた"},
{no:1967,en:"routine",ja:"決まりきった仕事"},
{no:1968,en:"actual",ja:"実際の"},
{no:1969,en:"reality",ja:"現実"},
{no:1970,en:"evident",ja:"明白な"},
{no:1971,en:"apparent",ja:"明白な"},
{no:1972,en:"obvious",ja:"明白な"},
{no:1973,en:"stubborn",ja:"頑固な"},
{no:1974,en:"coward",ja:"臆病者"},
{no:1975,en:"vain",ja:"むだな"},
{no:1976,en:"selfish",ja:"わがままな"},
{no:1977,en:"notorious",ja:"悪名高い"},
{no:1978,en:"negative",ja:"否定的な"},
{no:1979,en:"prejudice",ja:"偏見"},
{no:1980,en:"idle",ja:"仕事をしていない"},
{no:1981,en:"indifferent",ja:"無関心な"},
{no:1982,en:"efficient",ja:"効率的な"},
{no:1983,en:"punctual",ja:"時間を厳守する"},
{no:1984,en:"prompt",ja:"即座の"},
{no:1985,en:"precise",ja:"正確な"},
{no:1986,en:"exact",ja:"正確な"},
{no:1987,en:"odd",ja:"奇妙な"},
{no:1988,en:"unusual",ja:"ふつうではない"},
{no:1989,en:"peculiar",ja:"妙な"},
{no:1990,en:"alien",ja:"異質な"},
{no:1991,en:"irregular",ja:"不規則な"},
{no:1992,en:"absurd",ja:"不合理な"},
{no:1993,en:"silly",ja:"愚かな"},
{no:1994,en:"crucial",ja:"決定的な"},
{no:1995,en:"incredible",ja:"信じられないほどすごい"},
{no:1996,en:"focus",ja:"…を～に集中させる"},
{no:1997,en:"dim",ja:"薄暗い"},
{no:1998,en:"visible",ja:"目に見える"},
{no:1999,en:"vision",ja:"視力"},
{no:2000,en:"insight",ja:"洞察（力）"},
{no:2001,en:"element",ja:"要素"},
{no:2002,en:"factor",ja:"要因"},
{no:2003,en:"aspect",ja:"面"},
{no:2004,en:"detail",ja:"細部"},
{no:2005,en:"portion",ja:"部分"},
{no:2006,en:"section",ja:"部分"},
{no:2007,en:"feature",ja:"特徴"},
{no:2008,en:"substitute",ja:"代わり（のもの）"},
{no:2009,en:"various",ja:"さまざまな"},
{no:2010,en:"acquaintance",ja:"知り合い"},
{no:2011,en:"companion",ja:"仲間"},
{no:2012,en:"crew",ja:"乗組員"},
{no:2013,en:"consent",ja:"承諾"},
{no:2014,en:"affection",ja:"愛情"},
{no:2015,en:"community",ja:"地域社会"},
{no:2016,en:"mutual",ja:"相互の"},
{no:2017,en:"adequate",ja:"十分な"},
{no:2018,en:"sufficient",ja:"十分な"},
{no:2019,en:"appropriate",ja:"適切な"},
{no:2020,en:"medium",ja:"中間の"},
{no:2021,en:"moderate",ja:"適度の"},
{no:2022,en:"steady",ja:"安定した"},
{no:2023,en:"stable",ja:"安定した"},
{no:2024,en:"mere",ja:"ほんの"},
{no:2025,en:"slight",ja:"軽い"},
{no:2026,en:"scale",ja:"体重計"},
{no:2027,en:"degree",ja:"（温度・角度の）度"},
{no:2028,en:"fierce",ja:"獰猛な"},
{no:2029,en:"hostile",ja:"敵意のある"},
{no:2030,en:"passion",ja:"激情"},
{no:2031,en:"violence",ja:"暴力"},
{no:2032,en:"temper",ja:"短気"},
{no:2033,en:"upset",ja:"を動揺させる"},
{no:2034,en:"urge",ja:"〈人〉に～するよう強く促す"},
{no:2035,en:"impulse",ja:"（心の）衝動"},
{no:2036,en:"harsh",ja:"厳しい"},
{no:2037,en:"tackle",ja:"に取り組む"},
{no:2038,en:"worthy",ja:"値する"},
{no:2039,en:"merit",ja:"長所"},
{no:2040,en:"talent",ja:"才能"},
{no:2041,en:"fault",ja:"欠点"},
{no:2042,en:"mental",ja:"精神の"},
{no:2043,en:"psychology",ja:"心理学"},
{no:2044,en:"emotion",ja:"（強い）感情"},
{no:2045,en:"conscious",ja:"自覚して"},
{no:2046,en:"fancy",ja:"～したいと思う"},
{no:2047,en:"physical",ja:"身体の"},
{no:2048,en:"naked",ja:"裸の"},
{no:2049,en:"therapy",ja:"治療（法）"},
{no:2050,en:"blush",ja:"顔を赤らめる"},
{no:2051,en:"frequent",ja:"頻繁な"},
{no:2052,en:"apt",ja:"～しがちである"},
{no:2053,en:"lean",ja:"傾く"},
{no:2054,en:"tend",ja:"～しがちである"},
{no:2055,en:"trend",ja:"動向"},
{no:2056,en:"fate",ja:"運命"},
{no:2057,en:"fortune",ja:"幸運"},
{no:2058,en:"fortunate",ja:"幸運な"},
{no:2059,en:"incident",ja:"できごと"},
{no:2060,en:"inevitable",ja:"避けられない"},
{no:2061,en:"probable",ja:"たぶん…だろう"},
{no:2062,en:"prospect",ja:"（成功の）見込み"},
{no:2063,en:"consequence",ja:"結果"},
{no:2064,en:"burden",ja:"重荷"},
{no:2065,en:"conflict",ja:"対立"},
{no:2066,en:"contrary",ja:"（正）反対"},
{no:2067,en:"pressure",ja:"圧力"},
{no:2068,en:"hazard",ja:"危険要素"},
{no:2069,en:"recession",ja:"不況"},
{no:2070,en:"notion",ja:"考え"},
{no:2071,en:"concept",ja:"概念"},
{no:2072,en:"myth",ja:"間違った通念"},
{no:2073,en:"clue",ja:"手がかり"},
{no:2074,en:"conscience",ja:"良心"},
{no:2075,en:"explanation",ja:"説明"},
{no:2076,en:"rational",ja:"理性的な"},
{no:2077,en:"defect",ja:"欠陥"},
{no:2078,en:"doubtful",ja:"疑わしい"},
{no:2079,en:"obstacle",ja:"障害（物）"},
{no:2080,en:"threat",ja:"脅威"},
{no:2081,en:"risk",ja:"危険"},
{no:2082,en:"solution",ja:"解決（策）"},
{no:2083,en:"overcome",ja:"に打ち勝つ"},
{no:2084,en:"succeed",ja:"…に成功する"},
{no:2085,en:"extent",ja:"範囲"},
{no:2086,en:"parallel",ja:"平行の"},
{no:2087,en:"angle",ja:"角度"},
{no:2088,en:"billion",ja:"10億"},
{no:2089,en:"tough",ja:"困難な"},
{no:2090,en:"delicate",ja:"微妙な"},
{no:2091,en:"presence",ja:"存在"},
{no:2092,en:"instance",ja:"例"},
{no:2093,en:"porcelain",ja:"磁器"},
{no:2094,en:"elderly",ja:"年配の"},
{no:2095,en:"fellow",ja:"男"},
{no:2096,en:"household",ja:"家族"},
{no:2097,en:"immigrant",ja:"（外国からの）移民"},
{no:2098,en:"resident",ja:"住民"},
{no:2099,en:"pedestrian",ja:"歩行者"},
{no:2100,en:"status",ja:"地位"},
{no:2101,en:"strive",ja:"努力する"},
{no:2102,en:"sustain",ja:"を持続させる"},
{no:2103,en:"stick",ja:"棒切れ"},
{no:2104,en:"function",ja:"機能"},
{no:2105,en:"superficial",ja:"表面的な"},
{no:2106,en:"reward",ja:"ほうび"},
{no:2107,en:"remarkable",ja:"注目すべき"},
{no:2108,en:"resource",ja:"資源"},
{no:2109,en:"specific",ja:"明確な"},
{no:2110,en:"aware",ja:"気づいている"},
{no:2111,en:"assign",ja:"を割り当てる"},
{no:2112,en:"deserve",ja:"を受けるに値する"},
{no:2113,en:"possess",ja:"を所有する"},
{no:2114,en:"exceed",ja:"（限度）を超える"},
{no:2115,en:"freeze",ja:"凍る"},
{no:2116,en:"bathe",ja:"を入浴させる"},
{no:2117,en:"corporation",ja:"企業"},
{no:2118,en:"colleague",ja:"同僚"},
{no:2119,en:"interaction",ja:"交流"},
{no:2120,en:"agent",ja:"代理人"},
{no:2121,en:"executive",ja:"管理職"},
{no:2122,en:"cooperation",ja:"協力"},
{no:2123,en:"cope",ja:"…にうまく対処する"},
{no:2124,en:"formation",ja:"編成"},
{no:2125,en:"frankly",ja:"率直に"},
{no:2126,en:"thus",ja:"したがって"},
{no:2127,en:"somehow",ja:"何とかして"},
{no:2128,en:"altogether",ja:"まったく"},
{no:2129,en:"moreover",ja:"そのうえ"},
{no:2130,en:"nevertheless",ja:"それにもかかわらず"},
{no:2131,en:"regardless",ja:"それでも"},
{no:2132,en:"immune",ja:"免疫のある"},
{no:2133,en:"infection",ja:"感染症"},
{no:2134,en:"nutrition",ja:"栄養摂取"},
{no:2135,en:"calorie",ja:"カロリー"},
{no:2136,en:"obesity",ja:"肥満"},
{no:2137,en:"surgery",ja:"（外科）手術"},
{no:2138,en:"sneeze",ja:"くしゃみをする"},
{no:2139,en:"ingredient",ja:"材料"},
{no:2140,en:"vaccine",ja:"ワクチン"},
{no:2141,en:"pandemic",ja:"パンデミック"},
{no:2142,en:"vast",ja:"膨大な"},
{no:2143,en:"enormous",ja:"巨大な"},
{no:2144,en:"numerous",ja:"多数の"},
{no:2145,en:"approximately",ja:"およそ"},
{no:2146,en:"somewhat",ja:"いくらか"},
{no:2147,en:"multiple",ja:"多数の"},
{no:2148,en:"absolute",ja:"絶対的な"},
{no:2149,en:"entire",ja:"全体の"},
{no:2150,en:"extreme",ja:"極度の"},
{no:2151,en:"ultimate",ja:"最終的な"},
{no:2152,en:"maximum",ja:"最大限の"},
{no:2153,en:"supreme",ja:"最高の"},
{no:2154,en:"genuine",ja:"心からの"},
{no:2155,en:"utility",ja:"公共料金"},
{no:2156,en:"deposit",ja:"を預金する"},
{no:2157,en:"withdraw",ja:"（お金）を引き出す"},
{no:2158,en:"questionnaire",ja:"アンケート用紙"},
{no:2159,en:"detergent",ja:"洗剤"},
{no:2160,en:"dye",ja:"染料"},
{no:2161,en:"appliance",ja:"（家庭用の）電気器具"},
{no:2162,en:"antibiotic",ja:"抗生物質"},
{no:2163,en:"diagnosis",ja:"診断"},
{no:2164,en:"diabetes",ja:"糖尿病"},
{no:2165,en:"pneumonia",ja:"肺炎"},
{no:2166,en:"dementia",ja:"認知症"},
{no:2167,en:"chronic",ja:"慢性の"},
{no:2168,en:"epidemic",ja:"（病気の）流行"},
{no:2169,en:"asthma",ja:"ぜんそく"},
{no:2170,en:"heal",ja:"を癒やす"},
{no:2171,en:"evacuation",ja:"避難"},
{no:2172,en:"hygiene",ja:"清潔"},
{no:2173,en:"devastating",ja:"壊滅的な"},
{no:2174,en:"donation",ja:"寄付"},
{no:2175,en:"blackout",ja:"停電"},
{no:2176,en:"infrastructure",ja:"インフラ"},
{no:2177,en:"website",ja:"ホームページ"},
{no:2178,en:"browse",ja:"を閲覧する"},
{no:2179,en:"hack",ja:"不法侵入する"},
{no:2180,en:"copyright",ja:"著作権"},
{no:2181,en:"text",ja:"文章"},
{no:2182,en:"revenue",ja:"収益"},
{no:2183,en:"deficit",ja:"赤字"},
{no:2184,en:"fluctuation",ja:"変動"},
{no:2185,en:"launch",ja:"（新製品）を発売する"},
{no:2186,en:"estate",ja:"地所"},
{no:2187,en:"bureaucratic",ja:"官僚的な"},
{no:2188,en:"diplomacy",ja:"外交"},
{no:2189,en:"enforce",ja:"（法律など）を遵守させる"},
{no:2190,en:"fiscal",ja:"財政上の"},
{no:2191,en:"regime",ja:"政権"},
{no:2192,en:"census",ja:"国勢調査"},
{no:2193,en:"corruption",ja:"汚職"},
{no:2194,en:"administration",ja:"政権"},
{no:2195,en:"subsidy",ja:"補助金"},
{no:2196,en:"bribe",ja:"わいろ"},
{no:2197,en:"session",ja:"会議"},
{no:2198,en:"refugee",ja:"難民"},
{no:2199,en:"tolerance",ja:"寛容"},
{no:2200,en:"transition",ja:"移行"},
{no:2201,en:"negotiate",ja:"交渉する"},
{no:2202,en:"controversial",ja:"物議をかもす"},
{no:2203,en:"sanction",ja:"制裁"},
{no:2204,en:"boundary",ja:"境界（線）"},
{no:2205,en:"mission",ja:"任務"},
{no:2206,en:"warfare",ja:"戦闘行為"},
{no:2207,en:"integrate",ja:"を統合する"},
{no:2208,en:"branch",ja:"支店"},
{no:2209,en:"masterpiece",ja:"（最高）傑作"},
{no:2210,en:"opponent",ja:"相手"},
{no:2211,en:"passage",ja:"道"},
{no:2212,en:"scheme",ja:"計画"},
{no:2213,en:"shed",ja:"小屋"},
{no:2214,en:"stem",ja:"茎"},
{no:2215,en:"trait",ja:"（人・物の）特性"},
{no:2216,en:"ease",ja:"容易さ"},
{no:2217,en:"gross",ja:"総体の"},
{no:2218,en:"initial",ja:"初めの"},
{no:2219,en:"acute",ja:"鋭い"},
{no:2220,en:"casual",ja:"くだけた"},
{no:2221,en:"ethical",ja:"倫理的な"},
{no:2222,en:"indispensable",ja:"欠かせない"},
{no:2223,en:"worthwhile",ja:"価値のある"},
{no:2224,en:"as",ja:"…するときに"},
{no:2225,en:"that",ja:"それ"},
{no:2226,en:"but",ja:"ほんの"},
{no:2227,en:"while",ja:"しばらく（の間）"},
{no:2228,en:"if",ja:"…かどうか"},
{no:2229,en:"whether",ja:"…かどうか"},
{no:2230,en:"much",ja:"非常に"},
{no:2231,en:"otherwise",ja:"別の方法で"},
{no:2232,en:"once",ja:"1度"},
{no:2233,en:"since",ja:"…して以来"}
];
